const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=n=>fs.readFileSync('backend/apps-script-v6/'+n+'.gs','utf8');
const campaignId='CMP-CAMPANA-A-HA-PRIORITARIA',scopeId='SCOPE-CAMPANA-A-HA-PRIORITARIA';
const queue=Array.from({length:109},(_,i)=>({jobId:'J'+i,campaignId,accountId:'A'+i%23,contactId:'C'+i,email:`person${i}@example.com`,status:'SENT',playbookId:'Retention',preferredLanguage:i<85?'EN':i<96?'ES':'PT',subject:'Persisted subject '+i,htmlBody:`<html><body><h1>Historical Retention ${i}</h1><a href="https://example.com">Link</a></body></html>`,replyTo:'sender@example.com',processedAt:'2026-09-20T10:00:00Z'}));
queue.push({jobId:'FAILED',status:'FAILED',campaignId},...Array.from({length:139},(_,i)=>({jobId:'STOP'+i,status:'STOPPED',campaignId})));
const tables={MKT_EMAIL_QUEUE:queue,MKT_CAMPAIGNS:[{campaignId,campaignName:'Old',campaignType:'Retention',objective:'Retention',service:'Old',status:'Old',createdAt:'original',custom:'keep'}],MKT_CAMPAIGN_SCOPES:[{scopeId,campaignId,audienceId:'aud',campaignType:'Retention',opportunityType:'Retention',custom:'keep'}],MKT_SCOPE_ACCOUNTS:[{scopeId,accountId:'A0'}],MKT_EMAIL_EVENTS:Array.from({length:11},(_,i)=>({jobId:'J'+i,eventType:'BOUNCE',reasonCode:i<4?'HARD_BOUNCE':'BLOCKED',occurredAt:'2026-09-21T00:00:00Z',source:'GMAIL_DSN'}))};
const before=JSON.stringify(queue),membership=JSON.stringify(tables.MKT_SCOPE_ACCOUNTS);let writes=0,locked=0;
function forbidden(){throw Error('FORBIDDEN SIDE EFFECT');}
const ctx={console,Date,Set,String,Object,Number,Array,JSON,isFinite,v6Rows_:n=>tables[n]||[],GmailApp:{sendEmail:forbidden},v6AuraEmailHtml_:forbidden,v6AuraEmailCopy_:forbidden,auraProcessEmailQueue:forbidden,PropertiesService:{getScriptProperties:forbidden},LockService:{getScriptLock:()=>({waitLock(){locked++;},releaseLock(){locked--;}})},v6Sheet_:n=>({getDataRange:()=>({getValues:()=>{const keys=Object.keys(tables[n][0]);return[keys,...tables[n].map(r=>keys.map(k=>r[k]))];}}),getRange:(r,c)=>({setValues:v=>{assert(locked);const keys=Object.keys(tables[n][0]);tables[n][r-2][keys[c-1]]=v[0][0];writes++;}})})};vm.createContext(ctx);
['MarketingV6AuraCreativeApproval','MarketingV6AuraEmailPerformance','MarketingV6AuraMetadataReconciliation','MarketingV6RouterExtension'].forEach(n=>vm.runInContext(source(n),ctx));
let report=ctx.v6AuraEmailPerformance_();assert.equal(report.summary.sentRecipientJobs,109);assert.equal(report.summary.sentUniqueEmails,109);assert.equal(report.summary.sentUniqueAccounts,23);assert.equal(report.summary.failed,1);assert.equal(report.summary.bounced,11);assert.equal(report.summary.replied,0);assert.equal(report.summary.opened,null);assert.equal(report.summary.clicked,null);assert(!JSON.stringify(report).includes('htmlBody'));
const changes=ctx.RUN_AURA_CAMPANA_A_RECONCILE_METADATA_ONLY();assert.equal(changes.status,'RECONCILED');assert(changes.diff[0].changes.some(c=>c.before==='Retention'&&c.after==='Activation'));assert.equal(tables.MKT_CAMPAIGNS[0].createdAt,'original');assert.equal(tables.MKT_CAMPAIGNS[0].custom,'keep');assert.equal(tables.MKT_CAMPAIGN_SCOPES[0].audienceId,'aud');assert.equal(JSON.stringify(tables.MKT_SCOPE_ACCOUNTS),membership);const firstWrites=writes;assert.equal(ctx.v6AuraCampanaAReconcileMetadataOnly_().changedFields,0);assert.equal(writes,firstWrites);
const detail=ctx.v6AuraEmailPerformanceJob_({jobId:'J0'});assert.equal(detail.subject,queue[0].subject);assert.equal(detail.htmlBody,queue[0].htmlBody);assert.equal(detail.sentFamily,'Retention');assert.equal(detail.currentCampaignFamily,'Activation');assert.equal(detail.creativeProvenance,'LEGACY_PRE_CANONICAL');assert.equal(detail.integrityStatus,'LEGACY_CHECKSUM_NOT_AVAILABLE');assert.equal(detail.creativeId,'');assert.equal(detail.bounceReason,'HARD_BOUNCE');assert.equal(detail.opened,null);assert.equal(detail.clicked,null);assert.equal(JSON.stringify(queue),before);assert(!('gmailMessageId' in detail));
assert.equal(ctx.v6AuraEmailPerformanceJob_({}).status,'INVALID_REQUEST');assert.equal(ctx.v6AuraEmailPerformanceJob_({jobId:'absent'}).status,'NOT_FOUND');
const future={...queue[0],jobId:'future',playbookId:'Activation',creativeId:'creative',creativeApprovalId:'approval'};future.recipientContentChecksum=ctx.v6AuraJobContentChecksum_(future.subject,future.htmlBody);queue.push(future);assert.equal(ctx.v6AuraEmailPerformanceJob_({jobId:'future'}).creativeProvenance,'CAMPAIGN_STUDIO_APPROVED');assert.equal(ctx.v6AuraEmailPerformanceJob_({jobId:'future'}).integrityStatus,'VERIFIED');future.subject+='drift';assert.equal(ctx.v6AuraEmailPerformanceJob_({jobId:'future'}).integrityStatus,'MISMATCH');queue.pop();
vm.runInContext(fs.readFileSync('backend/apps-script-legacy-v55/MarketingV55Backend.gs','utf8'),ctx);ctx.mktV55Json_=(_,v)=>v;ctx.mktV55Audit_=()=>{};ctx.mktV55AssertToken_=token=>{if(token!=='private')throw Error('Unauthorized');};assert.equal(ctx.handleMarketingV55Api_({parameter:{action:'v6AuraEmailPerformanceJob',jobId:'J0'}},'GET').ok,false);assert.equal(ctx.handleMarketingV55Api_({parameter:{action:'v6AuraEmailPerformanceJob',jobId:'J0',token:'private'}},'GET').result.htmlBody,queue[0].htmlBody);
assert.equal(JSON.stringify(queue),before);console.log('PASS historical fixture: 109 sent recipients / 23 unique accounts; exact immutable payload, provenance, checksums, auth, metadata-only reconciliation');
