const assert=require('assert'),fs=require('fs'),vm=require('vm');
const src=n=>fs.readFileSync('backend/apps-script-v6/'+n+'.gs','utf8');
class Sheet{constructor(rows=[]){this.rows=rows;}getLastRow(){return this.rows.length;}getLastColumn(){return Math.max(0,...this.rows.map(r=>r.length));}getRange(r,c,n,w){return{getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>(this.rows[r-1+i]||[])[c-1+j]||'')),setValues:v=>v.forEach((row,i)=>{this.rows[r-1+i]||=[];row.forEach((x,j)=>this.rows[r-1+i][c-1+j]=x);})};}}
const sheets={},tables={MKT_EMAIL_QUEUE:[{jobId:'j',campaignId:'c',accountId:'a',contactId:'p',email:'p@example.com',status:'SENT',processedAt:'2026-09-01T00:00:00Z'}],MKT_EMAIL_EVENTS:[],MKT_EXCLUSIONS:[],MKT_CONTACTS_SECURE:[{contactId:'p',emailStatus:'VALID'}]},props={AURA_SEND_MODE:'DRY_RUN'},triggers=[];
let created=0,searches=[],fail=false;
const ctx={Date,Math,Number,String,Object,Array,JSON,isFinite,console,MKT_V6_DATA_HUB_ID:'hub',v6Sheet_:n=>sheets[n],SpreadsheetApp:{openById:()=>({insertSheet:n=>{created++;return sheets[n]=new Sheet();}})},v6Rows_:n=>tables[n]||[],v6UpsertByKey_:(n,ks,r)=>{const rows=tables[n]||=[];const i=rows.findIndex(x=>ks.every(k=>x[k]===r[k]));if(i<0)rows.push(r);else rows[i]=r;},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>{assert.notEqual(k,'AURA_SEND_MODE');props[k]=v;},deleteProperty:k=>{assert.notEqual(k,'AURA_SEND_MODE');delete props[k];}})},ScriptApp:{getProjectTriggers:()=>triggers.slice(),newTrigger:handler=>({timeBased:()=>({everyHours:n=>{assert.equal(n,1);return{create:()=>{const t={getHandlerFunction:()=>handler};triggers.push(t);return t;}};}})}),deleteTrigger:t=>triggers.splice(triggers.indexOf(t),1)},GmailApp:{search:(query,start,size)=>{assert.equal(size,50);searches.push({query,start});return Array.from({length:Math.min(50,121-start)},()=>({getMessages:()=>{if(fail)throw Error('temporary');return [];}}));},sendEmail(){throw Error('SEND FORBIDDEN');}},auraProcessEmailQueue(){throw Error('DISPATCH FORBIDDEN');}};
vm.createContext(ctx);['MarketingV6SchemaMigration','MarketingV6ResponseEvents','MarketingV6RecipientResolution','MarketingV6AuraEmailPerformance'].forEach(n=>vm.runInContext(src(n),ctx));
// Full governed migration creates the missing events sheet and preserves historical rows.
Object.keys(ctx.MKT_V6_CONTACT_RECIPIENT_SCHEMA).filter(n=>n!=='MKT_EMAIL_EVENTS').forEach(n=>sheets[n]=new Sheet([Array.from(ctx.MKT_V6_CONTACT_RECIPIENT_SCHEMA[n])]));
ctx.v6EnsureContactRecipientSchema_();assert.equal(created,1);assert.deepEqual(Array.from(sheets.MKT_EMAIL_EVENTS.rows[0]),Array.from(ctx.AURA_EMAIL_EVENT_HEADERS_));sheets.MKT_EMAIL_EVENTS.rows.push(['historical']);ctx.v6EnsureContactRecipientSchema_();assert.equal(created,1);assert.deepEqual(sheets.MKT_EMAIL_EVENTS.rows[1],['historical']);
// Installer is wired into both bootstrap and the existing hourly cycle.
assert(src('MarketingV6AuraBootstrap').includes('v6AuraInstallDsnTrigger_()'));assert(src('MarketingV6AuraAutomation').includes('v6AuraInstallDsnTrigger_()'));
ctx.v6AuraInstallDsnTrigger_();ctx.v6AuraInstallDsnTrigger_();assert.equal(triggers.length,1);triggers.push({getHandlerFunction:()=> 'auraIngestGmailDsn'});ctx.v6AuraInstallDsnTrigger_();assert.equal(triggers.length,1);
ctx.auraIngestGmailDsn();assert.equal(JSON.parse(props.AURA_DSN_PROGRESS).start,50);fail=true;assert.throws(()=>ctx.auraIngestGmailDsn(),/temporary/);assert.equal(JSON.parse(props.AURA_DSN_PROGRESS).start,50);fail=false;ctx.auraIngestGmailDsn();assert.equal(JSON.parse(props.AURA_DSN_PROGRESS).start,100);ctx.auraIngestGmailDsn();assert.equal(props.AURA_DSN_PROGRESS,undefined);assert.deepEqual(searches.map(x=>x.start),[0,50,50,100]);assert.equal(new Set(searches.map(x=>x.query)).size,1);assert.equal(props.AURA_SEND_MODE,'DRY_RUN');
const message={getId:()=> 'blocked',getDate:()=>new Date('2026-09-02T00:00:00Z'),getRawContent:()=> 'Content-Type: message/delivery-status\nFinal-Recipient: rfc822; p@example.com\nStatus: 5.4.1\nDiagnostic-Code: smtp; 550 5.4.1 blocked'};
ctx.v6AuraIngestDsnMessage_(message);const exclusion=tables.MKT_EXCLUSIONS[0];assert.equal(exclusion.reasonCode,'BLOCKED');assert.equal(tables.MKT_CONTACTS_SECURE[0].emailStatus,'VALID');assert(ctx.v6RecipientActiveExclusion_(tables.MKT_EXCLUSIONS,'a','p',new Date()));assert.equal(ctx.v6RecipientActiveExclusion_(tables.MKT_EXCLUSIONS,'a','sibling',new Date()),null);assert(tables.MKT_EMAIL_EVENTS.some(e=>e.eventType==='BOUNCE'&&e.reasonCode==='BLOCKED'));assert.equal(ctx.v6AuraEmailPerformance_().rows[0].bounceAt,'2026-09-02T00:00:00.000Z');
ctx.v6AuraIngestDsnMessage_(message);assert.equal(tables.MKT_EXCLUSIONS.length,1);exclusion.active=false;exclusion.status='CLEARED';ctx.v6AuraIngestDsnMessage_(message);assert.equal(ctx.v6RecipientActiveExclusion_(tables.MKT_EXCLUSIONS,'a','p',new Date()),null);
const window={document:{addEventListener(){}},addEventListener(){}};vm.runInNewContext(fs.readFileSync('assets/js/aura-dashboard-v1.js','utf8'),{window,console,Number,Set});
for(const key of ['sentAt','failedAt','replyAt','bounceAt','openAt','clickAt']){const rows=[{email:'p@example.com',[key]:'2026-09-10T00:00:00Z'}];assert.equal(window.DGL_AURA_PERFORMANCE.filter(rows,{from:'2026-09-10',to:'2026-09-10'}).length,1,key);assert.equal(window.DGL_AURA_PERFORMANCE.filter(rows,{from:'2026-09-11'}).length,0,key);}
console.log('PASS schema bootstrap, hourly trigger, durable paging/retry, BLOCKED contact eligibility/manual clear, unchanged mode, all six event dates');
