const fs=require("fs"),assert=require("assert"),path=require("path");
const source=fs.readFileSync(path.join(__dirname,"..","assets/js/marketing-backend-adapter-v55.js"),"utf8");
const requestsUi=fs.readFileSync(path.join(__dirname,"..","assets/js/campaign-opportunity-center-v5.js"),"utf8");
const automation=fs.readFileSync(path.join(__dirname,"..","assets/js/marketing-automation-v55.js"),"utf8");
const agent=fs.readFileSync(path.join(__dirname,"..","assets/js/agent-control-v1.js"),"utf8");
const index=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8");
assert(source.includes('const TOKEN_KEY="dgl_mkt_v55_token_session"'));
assert(source.includes('const ENDPOINT="https://script.google.com/macros/s/AKfycbw1lzTl7iwqYNp_sp_y2So7rtTt-yUsTmb9DEtRy3tsrF9tUGxHy-exI6Vo8Qmy66GH/exec"'));
assert(source.includes("__dglV55Jsonp_"));
assert(source.includes('jsonp("v55Health",undefined,false)'));
assert(source.includes('if(requiresToken&&!token())'));
assert(!source.includes("fetch("));
assert(!/localStorage\.(?:setItem|getItem).*token/i.test(source));
assert(source.includes('params.set("payload",JSON.stringify(payload))'));
assert(source.includes('mutate("v55CreateCampaign",{requestId:payload.requestId,strategy:'));
for(const action of ["v55Requests","v55CreateRequest","v55UpdateRequest","v55Campaigns","v55CreateCampaign","v55RequestApproval","v55RecordApproval","v55ActivateCampaign","v55PauseCampaign","v55RecordResponse","v55StopAccount","v55Handoff","v55RecordOutcome","v55Activity"])assert(source.includes(`"${action}"`),`Missing ${action}`);
assert(source.includes('new CustomEvent("dgl:v55-backend-change"'));
assert(source.includes('status:"TEST DRAFT PREPARED",executionBoundary:"PRIVATE_BACKEND_REQUIRED"'));
assert(!/console\.(?:log|error|warn)/.test(source));
assert(requestsUi.includes('api?.isConnected?.()?api.getRequests():DEMO_REQUESTS'));
assert(requestsUi.includes('await adapter().createRequest(record)'));
assert(requestsUi.includes('AM Request saved in private backend.'));
assert(!requestsUi.includes("AMR-LOCAL"));
assert(automation.includes('api.createCampaign({requestId:r.id,strategy:context})'));
assert(automation.includes('await api.recordResponse(payload)'));
assert(agent.includes("FUTURE AUTOMATION LAYER"));
assert(index.includes('google-apps-script-bridge.js'));
assert(index.includes('marketing-backend-adapter-v55.js?v=20260826-2'));
console.log("V5.5 private backend adapter contract: PASS");
