const fs=require("fs"),vm=require("vm"),assert=require("assert"),path=require("path");
const session=new Map(),calls=[],backendCampaigns=[];
const request={id:"REQ-BACKEND-1",requestId:"REQ-BACKEND-1",amOwner:"AM Live",portfolioName:"Private Portfolio",accountName:"",accountCount:4,objective:"Quoted Not Booked",service:"FTL",messageAngle:"Quote Follow-Up",priority:"HIGH",commercialContext:"Private",requestedOutcome:"RFQ",targetWindow:"14 days",lane:"",qnbWindow:"0-14",audienceId:"AUD-PRIVATE",audienceCount:4,exclusions:"DNC",marketingStatus:"READY FOR MARKETING",campaignName:"QNB FTL Live"};
const adapter={isConnected:()=>true,getCampaigns:()=>backendCampaigns,getRequests:()=>[request],updateCampaign:(id,p)=>Object.assign(backendCampaigns.find(x=>x.id===id)||{},p),
  async createCampaign(payload){calls.push(["v55CreateCampaign",payload]);const c={id:"CMP-BACKEND-55",campaignId:"CMP-BACKEND-55",requestId:payload.requestId,name:payload.strategy.campaignName,status:"IN PREPARATION",amOwner:request.amOwner,objective:request.objective,service:request.service,accounts:4,playbookId:payload.strategy.playbookId};backendCampaigns.push(c);return c;},
  async updateRequest(id,patch){calls.push(["v55UpdateRequest",{id,patch}]);return{...request,...patch};},async requestApproval(id,data){calls.push(["v55RequestApproval",{id,data}]);return{status:"WAITING APPROVAL"};},
  async recordApproval(id,data){calls.push(["v55RecordApproval",{id,data}]);Object.assign(backendCampaigns[0],{status:"APPROVED",approved:true});return backendCampaigns[0];},async activateCampaign(id,data){calls.push(["v55ActivateCampaign",{id,data}]);return{status:"CAMPAIGN ACTIVE"};},async pauseCampaign(id,data){calls.push(["v55PauseCampaign",{id,data}]);return{status:"CAMPAIGN READY"};},
  async recordResponse(payload){calls.push(["v55RecordResponse",payload]);return{stop:{campaignId:payload.campaignId,accountId:payload.accountId,scope:"ACCOUNT_ONLY",remainingCampaignAccountsContinue:true},handoff:{campaignId:payload.campaignId,accountId:payload.accountId,amOwner:payload.amOwner}};},async stopAccount(p){calls.push(["v55StopAccount",p]);return p;},async handoffToAM(p){calls.push(["v55Handoff",p]);return p;},async recordOutcome(p){calls.push(["v55RecordOutcome",p]);return p;}};
const window={DGL_MARKETING_BACKEND_ADAPTER_V55:adapter,DGL_AM_REQUESTS:{getRequests:()=>[request]}};window.window=window;
const context=vm.createContext({window,sessionStorage:{getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v)},console,Date,Map,JSON});
const load=f=>vm.runInContext(fs.readFileSync(path.join(__dirname,"..",f),"utf8"),context,{filename:f});load("assets/js/marketing-playbooks-v55.js");load("assets/js/marketing-automation-v55.js");
(async()=>{const a=window.DGL_MARKETING_AUTOMATION_V55,prepared=await a.prepareCampaign(request.id);assert.equal(prepared.campaign.id,"CMP-BACKEND-55");assert.equal(prepared.context.sourceIndicator,"PRIVATE BACKEND");assert.equal(calls[0][0],"v55CreateCampaign");assert.equal(calls[0][1].requestId,request.id);assert.equal(calls[0][1].strategy.playbookId,"QNB_0_14");assert.equal(JSON.parse(session.get("dgl_v5_campaign_context")).campaignId,"CMP-BACKEND-55");
  assert.equal((await a.activateCampaign("CMP-BACKEND-55")).status,"WAITING APPROVAL");const rejected=await a.recordApproval("CMP-BACKEND-55",{approved:false});assert.equal(rejected.status,"WAITING APPROVAL");assert(!calls.some(x=>x[0]==="v55RecordApproval"));await a.requestApproval("CMP-BACKEND-55");await a.recordApproval("CMP-BACKEND-55",{approved:true,approvedBy:"Marketing",notes:"Reviewed"});assert(calls.some(x=>x[0]==="v55RequestApproval"));assert.equal(calls.find(x=>x[0]==="v55RecordApproval")[1].data.status,"APPROVED");assert.equal((await a.activateCampaign("CMP-BACKEND-55")).status,"CAMPAIGN ACTIVE");
  const response=await a.recordResponse("CMP-BACKEND-55","ACC-1",{responseType:"CUSTOMER_REPLIED",contactId:"CONTACT-1",channel:"EMAIL",summary:"Reply received"});assert(calls.some(x=>x[0]==="v55RecordResponse"));assert(!calls.some(x=>x[0]==="v55StopAccount"));assert(!calls.some(x=>x[0]==="v55Handoff"));assert.equal(response.stop.scope,"ACCOUNT_ONLY");assert.equal(response.remainingCampaignAccountsContinue,true);assert.equal(response.handoff.amOwner,"AM Live");console.log("V5.5 connected workflow: PASS");})().catch(e=>{console.error(e);process.exitCode=1});
