const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'backend/apps-script-v6/MarketingV6ContactIngestion.gs'),'utf8'),tables={MKT_ACCOUNTS:[],MKT_CONTACTS_SECURE:[]};
const context={Date,String,Array,Object,RegExp,Utilities:{DigestAlgorithm:{MD5:'MD5'},Charset:{UTF_8:'UTF8'},computeDigest(_a,text){const bytes=[];for(let i=0;i<16;i++)bytes.push((String(text).charCodeAt(i%String(text).length)||i)+i);return bytes;}},v6Rows_:name=>(tables[name]||[]).map(x=>({...x})),v6UpsertByKey_:(name,keys,record)=>{const rows=tables[name],at=rows.findIndex(row=>keys.every(k=>String(row[k]||'')===String(record[k]||'')));if(at<0)rows.push({...record});else rows[at]={...record};return record;}};
vm.createContext(context);vm.runInContext(source,context);
const payload={sourceSystem:'SALESFORCE',accounts:[{externalAccountId:'SF-ACCOUNT-1',accountName:'Example Account',amOwner:'Owner'}],contacts:[{contactId:'CON-1',externalAccountId:'SF-ACCOUNT-1',externalContactId:'SF-CONTACT-1',email:'VALID@EXAMPLE.INVALID'},{contactId:'CON-2',externalAccountId:'SF-ACCOUNT-1',externalContactId:'SF-CONTACT-2',email:''},{contactId:'CON-3',externalAccountId:'SF-ACCOUNT-1',externalContactId:'SF-CONTACT-3',email:'invalid',doNotContact:true}]};
const first=context.v6IngestAuthoritativeContacts_(payload),accountId=tables.MKT_ACCOUNTS[0].accountId;
assert(accountId.startsWith('ACC-'));assert.equal(tables.MKT_ACCOUNTS[0].externalAccountId,'SF-ACCOUNT-1');assert(tables.MKT_CONTACTS_SECURE.every(x=>x.accountId===accountId));assert.equal(tables.MKT_CONTACTS_SECURE[0].email,'valid@example.invalid');assert.equal(tables.MKT_CONTACTS_SECURE[1].emailStatus,'MISSING');assert.equal(tables.MKT_CONTACTS_SECURE[2].emailStatus,'INVALID');assert.equal(tables.MKT_CONTACTS_SECURE[2].doNotContact,true);assert.equal(first.contactsWithoutEmail,1);assert.equal(first.contactsInvalidEmail,1);assert.equal(first.contactsDoNotContact,1);assert(!JSON.stringify(first).includes('example.invalid'));
const second=context.v6IngestAuthoritativeContacts_(payload);assert.equal(tables.MKT_ACCOUNTS.length,1,'account upsert must be idempotent');assert.equal(tables.MKT_CONTACTS_SECURE.length,3,'contact upsert must be idempotent');assert.equal(second.accountsUpserted,1);assert.equal(second.contactsUpserted,3);
const crosswalk=context.v6ContactAccountId_({externalSystem:'SALESFORCE',externalAccountId:'SF-ACCOUNT-1'},tables.MKT_ACCOUNTS);assert.equal(crosswalk,accountId);assert(!/console\./.test(source));console.log('V6 authoritative contact ingestion: PASS');
