const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'backend/apps-script-v6'),read=n=>fs.readFileSync(path.join(dir,n),'utf8');
const frequency=read('MarketingV6FrequencyControl.gs'),pipeline=read('MarketingV6Pipeline.gs'),execution=read('MarketingV6ExecutionEngine.gs'),archive=read('MarketingV6DriveArchive.gs'),router=read('MarketingV6RouterExtension.gs'),studio=fs.readFileSync(path.join(root,'assets/js/campaign-studio-v5.js'),'utf8'),adapter=fs.readFileSync(path.join(root,'assets/js/marketing-backend-adapter-v55.js'),'utf8');
const now=new Date('2026-08-26T12:00:00Z');let ledger=[];const fctx={Date,Object,v6Sheet_:()=>({}),v6Rows_:()=>ledger};vm.createContext(fctx);vm.runInContext(frequency,fctx);fctx.v6Now_=()=>new Date(now);
function status(rows,p){ledger=rows;return fctx.v6FrequencyStatus_(Object.assign({accountId:'ACC-TEST',campaignType:'REACTIVATION'},p||{}));}
assert.equal(status([{accountId:'ACC-TEST',contactId:'',lastMarketingTouchAt:'2026-08-16T12:00:00Z',touches30d:2}]).status,'FREQUENCY CAP');
assert.equal(status([{accountId:'ACC-TEST',contactId:'CONTACT-TEST',lastMarketingTouchAt:'2026-08-16T12:00:00Z',touches30d:2}],{contactId:'CONTACT-TEST'}).contactTouches30d,2);
assert.equal(status([],{followUpDays:38}).status,'FOLLOW-UP TOO SOON');assert.equal(status([],{followUpDays:10}).status,'CLEAR');
assert.equal(status([{accountId:'ACC-TEST',cooldownUntil:'2026-09-10T00:00:00Z'}]).status,'COOLDOWN');
assert.equal(status([{accountId:'ACC-TEST',lastMarketingTouchAt:'2026-07-01T00:00:00Z',lastCommercialSignalAt:'2026-08-20T00:00:00Z',cooldownUntil:'2026-09-10T00:00:00Z'}],{newCommercialSignalEligible:true}).status,'CLEAR');
assert(['ACTIVE CAMPAIGN','HIGHER PRIORITY'].includes(status([{accountId:'ACC-TEST',activeCampaignId:'CAM-OLD',lastCampaignType:'QNB'}],{campaignId:'CAM-NEW'}).status));assert.equal(fctx.v6Priority_('QNB'),1);assert.equal(fctx.v6Priority_('Nurture'),5);assert(frequency.includes('IGNORED TEST DRAFT'));
let pipeRows=[],writes=[];const pctx={Date,Object,v6Rows_:()=>pipeRows,v6UpsertByKey_:(n,k,r)=>{writes=pipeRows=[r];return r;}};vm.createContext(pctx);vm.runInContext(pipeline,pctx);let row=pctx.v6UpsertPipelineStage_({accountId:'ACC-1',responseAt:'2026-08-26'});assert.equal(row.currentStage,'RESPONDED');row=pctx.v6UpsertPipelineStage_({accountId:'ACC-1',rfqAt:'2026-08-26'});assert.equal(row.currentStage,'RFQ RECEIVED');row=pctx.v6UpsertPipelineStage_({accountId:'ACC-1',quoteAt:'2026-08-26'});assert.equal(row.currentStage,'QUOTED');row=pctx.v6UpsertPipelineStage_({accountId:'ACC-1',loadAt:'2026-08-26'});assert.equal(row.currentStage,'LOAD / REACTIVATED');assert.equal(pipeRows.length,1);
assert.equal(pctx.v6PipelineAdvanced_(row.currentStage),true);assert.equal(pctx.v6PipelineWinner_({eligibilityStatus:'SUPPRESSED',priorityRank:1},{eligibilityStatus:'DETECTED',priorityRank:5}).eligibilityStatus,'DETECTED');
let executions=[];const ectx={Date,Object,Utilities:{getUuid:()=> '12345678-0000'},v6Rows_:()=>executions,v6UpsertByKey_:(n,k,r)=>{executions=[r];return r;},v6ArchiveExecution_:()=>({status:'ARCHIVE PENDING'})};vm.createContext(ectx);vm.runInContext(execution,ectx);const created=ectx.v6CreateExecution_({campaignId:'CAM-1'});assert.equal(executions.length,1);assert.equal(created.status,'CREATED');assert.equal(ectx.v6QueueExecution_({executionId:created.executionId}).status,'BLOCKED');assert(execution.includes('BULK PROVIDER NOT CONFIGURED'));assert(execution.includes("row.status==='COMPLETED'&&!row.executionCsvDriveFileId"));
assert(archive.includes("if(!Array.isArray(rows)||!rows.length)return {status:'ARCHIVE PENDING'"));assert(!archive.includes("'accountId,status"));assert(archive.includes('executionCsvDriveFileId:file.getId()'));assert(studio.includes('data-v5-test'));assert(adapter.includes('TEST_DRAFT_CREATED'));
assert(router.includes('v6PipelineTransition'));assert(router.includes('v6PipelineSyncSignals'));
for(const name of fs.readdirSync(dir).filter(n=>n.endsWith('.gs')))new vm.Script(read(name),{filename:name});
const changed=[frequency,pipeline,execution,archive,read('MarketingV6CopyUsage.gs'),read('MarketingV6CreativeUsage.gs')].join('\n');assert(!/@[a-z0-9.-]+\.[a-z]{2,}/i.test(changed));assert(!/https:\/\/drive\.google\.com/i.test(changed));
console.log('V6 production backend hardening: PASS');
