const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'backend/apps-script-v6/MarketingV6RecipientResolution.gs'),'utf8'),bridge=fs.readFileSync(path.join(root,'assets/js/campaign-scope-bridge-v6.js'),'utf8');
const tables={MKT_CAMPAIGNS:[],MKT_CAMPAIGN_SCOPES:[],MKT_SCOPE_ACCOUNTS:[],MKT_CONTACTS_SECURE:[],MKT_EXCLUSIONS:[],MKT_AUDIENCES:[]};
let schemaReady=true;const context={Date,String,Number,Array,Object,RegExp,v6RequireContactRecipientHeaders_(){if(!schemaReady)throw new Error('SCHEMA MIGRATION REQUIRED: MKT_AUDIENCES MISSING audienceRecipientId');return true;},v6Rows_:name=>(tables[name]||[]).map(x=>({...x})),v6UpsertByKey_:(name,keys,record)=>{const rows=tables[name],at=rows.findIndex(row=>keys.every(k=>String(row[k]||'')===String(record[k]||'')));if(at<0)rows.push({...record});else rows[at]={...record};return record;},v6FrequencyStatus_:p=>p.accountId==='ACC-CAP'?{status:'FREQUENCY CAP',eligible:false}:p.contactId==='CON-CAP'?{status:'FREQUENCY CAP',eligible:false}:{status:'CLEAR',eligible:true}};
vm.createContext(context);vm.runInContext(source,context);
function campaign(id,scope){tables.MKT_CAMPAIGNS.push({campaignId:id,scopeId:scope,campaignType:'REACTIVATION'});tables.MKT_CAMPAIGN_SCOPES.push({campaignId:id,scopeId:scope});}
function scoped(scope,accountId){tables.MKT_SCOPE_ACCOUNTS.push({scopeId:scope,accountId,eligibilityStatus:'DETECTED'});}
function contact(contactId,accountId,email,extra={}){tables.MKT_CONTACTS_SECURE.push({contactId,accountId,email,status:'ACTIVE',...extra});}
campaign('CMP-MULTI','SCOPE-MULTI');scoped('SCOPE-MULTI','ACC-1');contact('CON-1','ACC-1','one@example.invalid');contact('CON-2','ACC-1','two@example.invalid');let result=context.v6ResolveRecipients_({campaignId:'CMP-MULTI'});assert.equal(result.audienceResolved,true);assert.equal(result.eligibleContactCount,2);assert.equal(result.excludedContactCount,0);assert.deepEqual(Object.keys(result).sort(),['audienceResolved','audienceStatus','eligibleContactCount','excludedContactCount','exclusionStatus','exclusionsCleared','frequencyStatus','reasonCode'].sort());assert(!JSON.stringify(result).includes('@'));assert.equal(context.v6AudienceStatus_({campaignId:'CMP-MULTI'}).eligibleContactCount,2);
campaign('CMP-FILTERS','SCOPE-FILTERS');['ACC-NOEMAIL','ACC-INVALID','ACC-DNC','ACC-EXCLUSION','ACC-CAP','ACC-CONCAP'].forEach(id=>scoped('SCOPE-FILTERS',id));contact('CON-NOEMAIL','ACC-NOEMAIL','');contact('CON-INVALID','ACC-INVALID','invalid');contact('CON-DNC','ACC-DNC','dnc@example.invalid',{doNotContact:true});contact('CON-EXCLUSION','ACC-EXCLUSION','excluded@example.invalid');contact('CON-ACCAP','ACC-CAP','accountcap@example.invalid');contact('CON-CAP','ACC-CONCAP','contactcap@example.invalid');tables.MKT_EXCLUSIONS.push({contactId:'CON-EXCLUSION',active:true,status:'ACTIVE'});result=context.v6ResolveRecipients_({campaignId:'CMP-FILTERS'});assert.equal(result.audienceResolved,false);assert.equal(result.audienceStatus,'NO ELIGIBLE CONTACTS');assert.equal(result.eligibleContactCount,0);assert.equal(result.excludedContactCount,6);const reasons=tables.MKT_AUDIENCES.filter(x=>x.campaignId==='CMP-FILTERS'&&x.recordType==='RECIPIENT').map(x=>x.exclusionReason);for(const reason of ['EMAIL_MISSING','EMAIL_INVALID','DO_NOT_CONTACT','EXCLUSION_ACTIVE_EXCLUSION','FREQUENCY_FREQUENCY_CAP'])assert(reasons.includes(reason));
campaign('CMP-NOCONTACT','SCOPE-NOCONTACT');scoped('SCOPE-NOCONTACT','ACC-EMPTY');result=context.v6ResolveRecipients_({campaignId:'CMP-NOCONTACT'});assert.equal(result.audienceStatus,'NO CONTACTS AVAILABLE');assert.equal(result.eligibleContactCount,0);
campaign('CMP-MIXED','SCOPE-MIXED');scoped('SCOPE-MIXED','ACC-MIXED');contact('CON-MIXED-OK','ACC-MIXED','ok@example.invalid');contact('CON-MIXED-DNC','ACC-MIXED','blocked@example.invalid',{doNotContact:true});result=context.v6ResolveRecipients_({campaignId:'CMP-MIXED'});assert.equal(result.audienceResolved,true);assert.equal(result.eligibleContactCount,1);assert.equal(result.excludedContactCount,1);assert.equal(result.frequencyStatus,'CLEAR');assert.equal(result.exclusionStatus,'CLEAR');assert.equal(result.exclusionsCleared,true);
campaign('CMP-NOSCOPE','SCOPE-NOSCOPE');result=context.v6ResolveRecipients_({campaignId:'CMP-NOSCOPE'});assert.equal(result.audienceStatus,'ACCOUNT SCOPE UNRESOLVED');
const legacyExclusion={accountId:'ACC-1',reason:'LEGACY REASON',endDate:'2999-01-01',active:true},modernExclusion={accountId:'ACC-1',reasonCode:'MODERN_REASON',expiresAt:'2999-01-01',status:'ACTIVE'};assert.equal(context.v6RecipientExclusionReason_(legacyExclusion),'LEGACY REASON');assert.equal(context.v6RecipientExclusionReason_(modernExclusion),'MODERN_REASON');assert(context.v6RecipientActiveExclusion_([legacyExclusion],'ACC-1','CON-X',new Date()));assert(context.v6RecipientActiveExclusion_([modernExclusion],'ACC-1','CON-X',new Date()));tables.MKT_AUDIENCES.unshift({scopeId:'SCOPE-HISTORICAL',accountId:'ACC-HISTORICAL',legacyStatus:'HISTORICAL'});context.v6ResolveRecipients_({campaignId:'CMP-MULTI'});assert.equal(tables.MKT_AUDIENCES[0].legacyStatus,'HISTORICAL');schemaReady=false;assert.throws(()=>context.v6ResolveRecipients_({campaignId:'CMP-MULTI'}),/SCHEMA MIGRATION REQUIRED/);schemaReady=true;
const router=fs.readFileSync(path.join(root,'backend/apps-script-v6/MarketingV6RouterExtension.gs'),'utf8');assert(router.includes('v55ResolveRecipients:v6ResolveRecipients_'));assert(router.includes('v55AudienceStatus:v6AudienceStatus_'));assert(bridge.includes('await a.resolveRecipients(n.campaignId)'));assert(bridge.includes('await a.getAudienceStatus(n.campaignId)'));assert(source.includes("v6Rows_('MKT_CONTACTS_SECURE')")||source.includes("v6RecipientRows_('MKT_CONTACTS_SECURE')"));assert(source.includes("v6RecipientRows_('MKT_EXCLUSIONS')"));assert(!/return\s+\{[^}]*email\s*:/s.test(source));console.log('V6 production recipient resolution contract: PASS');
