const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),backend=fs.readFileSync(path.join(root,'backend/apps-script-v6/MarketingV6OpportunityEngine.gs'),'utf8'),frontend=fs.readFileSync(path.join(root,'assets/js/marketing-opportunity-engine-v6.js'),'utf8'),ui=fs.readFileSync(path.join(root,'assets/js/campaign-opportunities-v6.js'),'utf8');
const rows=[
  {accountId:'ACC-1',accountName:'SECRET ONE',contactId:'C-1',email:'hidden@example.invalid',amOwner:'Owner A',opportunityType:'Reactivation',service:'FTL',eligibilityStatus:'DETECTED',sourceReport:'CUENTAS',updatedAt:'2026-08-26T10:00:00Z'},
  {accountId:'ACC-2',accountName:'SECRET TWO',phone:'555',amOwner:'Owner A',opportunityType:'Quoted Not Booked',service:'LTL',qnbWindow:'0-14',eligibilityStatus:'SUPPRESSED',sourceReport:'LQS_SIN_RESPUESTA',updatedAt:'2026-08-27T10:00:00Z'},
  {accountId:'ACC-3',accountName:'SECRET THREE',amOwner:'Owner A',opportunityType:'Quoted Not Booked',service:'LTL',qnbWindow:'0-14',eligibilityStatus:'DETECTED',sourceReport:'LQS_SIN_RESPUESTA',updatedAt:'2026-08-27T09:00:00Z'},
  {accountId:'ACC-4',accountName:'SECRET FOUR',amOwner:'Owner B',opportunityType:'Retention',service:'Drayage',eligibilityStatus:'DETECTED'}
];
let pipeInput;const ctx={SpreadsheetApp:{},Logger:{log(){}},v6RefreshOpportunitiesFromReports_:()=>({status:'REPORT_SOURCE_SYNCED'}),v6PipelineSyncSignals_:payload=>(pipeInput=payload,{status:'SYNCED'})};vm.createContext(ctx);vm.runInContext(backend,ctx);ctx.v6Rows_=()=>rows;ctx.routeMarketingV6_=(action,payload)=>action==='v6Opportunities'?ctx.v6Opportunities_(payload):null;
const response=ctx.v6Opportunities_({});assert.equal(response.status,'READY');assert(Array.isArray(response.groups));assert.equal(response.summary.totalSignals,4);assert.equal(response.summary.eligibleAccounts,3);assert.equal(response.summary.suppressedAccounts,1);assert.equal(response.summary.groupCount,3);assert.equal(response.summary.campaignFamilies,3);
assert.equal(response.groups[0].priority,1);assert.equal(response.groups[0].detectedAccounts,2);assert.equal(response.groups[0].eligibleAccounts,1);assert.equal(response.groups[0].suppressedAccounts,1);assert.equal(response.groups[1].priority,2);assert.equal(response.groups[2].priority,3);
const forbidden=['accountId','accountName','contactId','contactName','email','phone','quoteId','loadId'];for(const key of forbidden)assert(!JSON.stringify(response).includes('"'+key+'"'));
const summary=ctx.v6OpportunitySummary_();assert.deepEqual(JSON.parse(JSON.stringify(summary.byType)),{'Reactivation':1,'Quoted Not Booked':2,'Retention':1});assert.equal(summary.lastEngineRun,'2026-08-27T10:00:00Z');
const run=ctx.v6RunOpportunityEngine_();assert(Array.isArray(pipeInput.opportunities),'Pipeline sync retains private rows internally');assert(Array.isArray(run.groups));assert(!Object.prototype.hasOwnProperty.call(run,'opportunities'));for(const key of forbidden)assert(!JSON.stringify(run).includes('"'+key+'"'));
const smoke=ctx.runV6BackendSmokeTest();assert.equal(smoke.ok,true);assert.equal(smoke.piiLeak,false);
const engineWindow={DGL_MARKETING_BACKEND_ADAPTER_V55:{isConnected:()=>true,v6Opportunities:async()=>response,v6OpportunitySummary:async()=>{throw new Error('fallback must not run');}}};vm.runInNewContext(frontend,{window:engineWindow,console,Map,Object,Array,String,Number,RegExp});
(async()=>{const loaded=await engineWindow.DGL_MARKETING_OPPORTUNITY_ENGINE_V6.load();assert.strictEqual(loaded.opportunities,response.groups);assert.equal(loaded.summary.totalSignals,4);for(const [message,status] of [['Unauthorized','BACKEND AUTHORIZATION FAILED'],['Private backend timeout','BACKEND TIMEOUT'],['Endpoint unavailable','V6 ENDPOINT ERROR']]){engineWindow.DGL_MARKETING_BACKEND_ADAPTER_V55.v6Opportunities=async()=>{throw new Error(message)};assert.equal((await engineWindow.DGL_MARKETING_OPPORTUNITY_ENGINE_V6.load()).status,status);}
assert(!ui.includes('RUN OPPORTUNITY ENGINE'));assert(!ui.includes('accountId'));assert(!ui.includes('accountName'));assert(!ui.includes('contactId'));assert(!ui.includes('email'));assert(ui.includes('data-v6-opportunity-status'));new vm.Script(backend);console.log('V6 safe opportunity aggregates: PASS');})().catch(error=>{console.error(error);process.exit(1);});
