const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
function load(file){const window={};vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),{window,console,sessionStorage:{getItem(){return null},setItem(){}}});return window;}
const opp=load('assets/js/marketing-opportunity-engine-v6.js').DGL_MARKETING_OPPORTUNITY_ENGINE_V6;
const grouped=opp.groupOpportunities([{amOwner:'A',opportunityType:'QNB',service:'FTL',qnbWindow:'0-14',eligibilityStatus:'DETECTED'},{amOwner:'A',opportunityType:'QNB',service:'FTL',qnbWindow:'0-14',eligibilityStatus:'SUPPRESSED'}]);
assert.equal(grouped.length,1);assert.equal(grouped[0].detectedAccounts,2);assert.equal(grouped[0].eligibleAccounts,1);assert.equal(grouped[0].suppressedAccounts,1);assert.equal(opp.priorityOf('QNB'),1);assert.equal(opp.priorityOf('Retention'),2);
const suppressed=opp.suppressCompeting([{accountId:'SAFE-1',opportunityType:'Fresh QNB'},{accountId:'SAFE-1',opportunityType:'Nurture'}]);assert.equal(suppressed[1].suppressionStatus,'HIGHER PRIORITY');
const freq=load('assets/js/marketing-frequency-control-v6.js').DGL_MARKETING_FREQUENCY_CONTROL_V6;assert.deepEqual(Array.from(freq.RULES.normalFollowUpDays),[10,14]);assert(!JSON.stringify(freq.RULES).includes('38'));assert.equal(freq.evaluate({accountTouches30d:2}).status,'FREQUENCY CAP');assert.equal(freq.evaluate({daysSinceNoResponse:20}).status,'COOLDOWN');
const pipe=load('assets/js/account-campaign-pipeline-v6.js').DGL_ACCOUNT_CAMPAIGN_PIPELINE_V6;const responded=pipe.transition({pendingTouchesStopped:false},'RESPONDED');assert.equal(responded.stopScope,'ACCOUNT_ONLY');assert.equal(responded.remainingCampaignAccountsContinue,true);
const execution=load('assets/js/campaign-execution-v6.js').DGL_CAMPAIGN_EXECUTION_V6;assert.equal(execution.readiness({}).ready,false);assert.equal(execution.canComplete({executionId:'EXEC-1',csvArchiveReady:false}),false);assert.equal(execution.canComplete({executionId:'EXEC-1',csvArchiveReady:true}),true);assert.equal(execution.provider.status,'BULK PROVIDER NOT CONFIGURED');
const creative=load('assets/js/creative-orchestration-v6.js').DGL_CREATIVE_ORCHESTRATION_V6;assert.equal(creative.eligible({approved:true,mediaType:'REAL PHOTO',daysSinceAccountUse:30,daysSinceLastUsed:90},{}),false);assert.equal(creative.selectAsset([],{objective:'Quoted Not Booked',allowNoHero:true}).creativeSystem,'DGL Executive Minimal');
const copy=load('assets/js/copy-engine-v6.js').DGL_COPY_ENGINE_V6,generated=copy.generate({service:'FTL',language:'en',businessSignal:'current lane demand'});assert.equal(generated.subjectCandidates.length,3);assert.equal(generated.bodyCandidates.length,2);assert.equal(copy.reusable(generated.fingerprint,[{fingerprint:generated.fingerprint,daysAgo:30}]),false);
const index=fs.readFileSync(path.join(root,'index.html'),'utf8'),app=fs.readFileSync(path.join(root,'assets/js/app.js'),'utf8'),opUI=fs.readFileSync(path.join(root,'assets/js/campaign-opportunities-v6.js'),'utf8'),studio=fs.readFileSync(path.join(root,'assets/js/campaign-studio-v5.js'),'utf8'),bridge=fs.readFileSync(path.join(root,'assets/js/google-apps-script-bridge.js'),'utf8');
assert(index.includes('campaign-opportunities-v6.js?v=20260826-2')&&index.includes('campaign-studio-v6.js'));assert(app.includes('Campaign Opportunities')&&app.includes('account-campaign-pipeline'));assert(opUI.includes('Automated opportunities detected from private commercial reports and account signals.')&&!opUI.includes('MANUAL EXCEPTION'));assert(studio.includes('getPreview'));assert(bridge.includes('account-campaign-pipeline'));
const adapter=fs.readFileSync(path.join(root,'assets/js/marketing-backend-adapter-v55.js'),'utf8');['v6Opportunities','v6FrequencyStatus','v6CreateExecution','v6CopyUsage','v6CreativeUsage'].forEach(x=>assert(adapter.includes(x)));
const publicJs=['marketing-opportunity-engine-v6.js','marketing-frequency-control-v6.js','campaign-execution-v6.js','creative-orchestration-v6.js','copy-engine-v6.js','campaign-opportunities-v6.js','account-campaign-pipeline-v6.js','campaign-studio-v6.js','marketing-os-v6.js'].map(x=>fs.readFileSync(path.join(root,'assets/js',x),'utf8')).join('\n');assert(!/customer@example|@[a-z0-9.-]+\.[a-z]{2,}/i.test(publicJs));assert(!publicJs.includes('1Har0llISmGa4oUDqqcathCXzMZVyyg13'));assert(!/localStorage\.setItem\([^)]*(token|contact|email)/i.test(publicJs));
console.log('V6 validation tests passed.');
