// DGL Acquisition Public Runtime — standalone Apps Script web app.
// Purpose: serve public-safe landing pages and receive lead forms.
// Deploy separately from the private Marketing OS backend.
// Script property required: MKT_DATA_HUB_ID

var ACQ_PUBLIC_LP_SHEET='MKT_ACQ_LANDING_PAGES';
var ACQ_PUBLIC_LEAD_SHEET='MKT_ACQ_LEADS';

function acqPubText_(v){return String(v==null?'':v).trim();}
function acqPubEsc_(v){return acqPubText_(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function acqPubBook_(){var id=PropertiesService.getScriptProperties().getProperty('MKT_DATA_HUB_ID');if(!id)throw new Error('MKT_DATA_HUB_ID NOT CONFIGURED');return SpreadsheetApp.openById(id);}
function acqPubRows_(name){var sh=acqPubBook_().getSheetByName(name);if(!sh||sh.getLastRow()<2)return [];var h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(acqPubText_),v=sh.getRange(2,1,sh.getLastRow()-1,h.length).getValues();return v.map(function(row){var r={};h.forEach(function(k,i){r[k]=row[i];});return r;});}
function acqPubAppend_(name,record){var sh=acqPubBook_().getSheetByName(name);if(!sh)throw new Error(name+' NOT FOUND');var h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(acqPubText_);sh.appendRow(h.map(function(k){return record[k]==null?'':record[k];}));}
function acqPubFindLanding_(slug){return acqPubRows_(ACQ_PUBLIC_LP_SHEET).filter(function(r){return acqPubText_(r.slug)===acqPubText_(slug)&&['LIVE','READY_TO_PUBLISH'].indexOf(acqPubText_(r.status))>=0;})[0]||null;}
function acqPubLabels_(lang){
  if(lang==='pt-BR')return {firstName:'Nome',lastName:'Sobrenome',company:'Empresa',email:'E-mail corporativo',phone:'Telefone',country:'País',service:'Serviço',origin:'Origem',destination:'Destino',notes:'Necessidade',submit:'ENVIAR NECESSIDADE',thanks:'Obrigado. Recebemos sua solicitação.'};
  if(lang==='es')return {firstName:'Nombre',lastName:'Apellido',company:'Empresa',email:'Email corporativo',phone:'Teléfono',country:'País',service:'Servicio',origin:'Origen',destination:'Destino',notes:'Requerimiento',submit:'ENVIAR REQUERIMIENTO',thanks:'Gracias. Recibimos su requerimiento.'};
  return {firstName:'First name',lastName:'Last name',company:'Company',email:'Business email',phone:'Phone',country:'Country',service:'Service',origin:'Origin',destination:'Destination',notes:'Requirement',submit:'SUBMIT REQUIREMENT',thanks:'Thank you. We received your requirement.'};
}
function doGet(e){
  var p=e&&e.parameter||{};if(p.health==='1')return ContentService.createTextOutput(JSON.stringify({ok:true,status:'DGL ACQUISITION PUBLIC RUNTIME'})).setMimeType(ContentService.MimeType.JSON);
  if(p.thanks==='1')return HtmlService.createHtmlOutput('<!doctype html><html><body style="font-family:Arial;padding:50px;text-align:center"><h2>Thank you.</h2><p>Your request was received.</p></body></html>');
  var landing=acqPubFindLanding_(p.slug);if(!landing)return HtmlService.createHtmlOutput('<!doctype html><html><body style="font-family:Arial;padding:50px"><h2>Page unavailable</h2><p>This landing page is not active.</p></body></html>').setTitle('DGL');
  return HtmlService.createHtmlOutput(acqPubLandingHtml_(landing,p)).setTitle(acqPubText_(landing.headline)||'DGL').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}
function doPost(e){
  var p=e&&e.parameter||{},honeypot=acqPubText_(p.website);if(honeypot)return HtmlService.createHtmlOutput('OK');
  var landing=acqPubFindLanding_(p.slug);if(!landing)return HtmlService.createHtmlOutput('Landing unavailable');
  var email=acqPubText_(p.email).toLowerCase(),company=acqPubText_(p.company),service=acqPubText_(p.service||landing.service);
  if(!company||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!service)return HtmlService.createHtmlOutput(acqPubErrorHtml_(landing.language));
  var now=new Date().toISOString(),leadId='LEAD-'+Utilities.getUuid().replace(/-/g,'').slice(0,18).toUpperCase();
  var record={leadId:leadId,landingPageId:landing.landingPageId,signalId:landing.signalId,createdAt:now,firstName:acqPubText_(p.firstName),lastName:acqPubText_(p.lastName),company:company,email:email,phone:acqPubText_(p.phone),country:acqPubText_(p.country),service:service,origin:acqPubText_(p.origin),destination:acqPubText_(p.destination),notes:acqPubText_(p.notes),utmSource:acqPubText_(p.utm_source||landing.utmSource),utmMedium:acqPubText_(p.utm_medium||landing.utmMedium),utmCampaign:acqPubText_(p.utm_campaign||landing.utmCampaign),validationStatus:'PENDING',dedupeStatus:'PENDING',existingContactId:'',existingAccountId:'',qualificationStatus:'PENDING',scoreStatus:'PENDING',routingStatus:'PENDING',salesforceLeadId:'',routedAt:'',updatedAt:now};
  var lock=LockService.getScriptLock();lock.waitLock(10000);try{acqPubAppend_(ACQ_PUBLIC_LEAD_SHEET,record);}finally{lock.releaseLock();}
  var labels=acqPubLabels_(landing.language);return HtmlService.createHtmlOutput('<!doctype html><html><body style="font-family:Arial;padding:50px;background:#fff;color:#101828;text-align:center"><div style="max-width:620px;margin:auto"><h2 style="color:#05035C">'+acqPubEsc_(labels.thanks)+'</h2><p>DGL Dedicated Ground Logistics</p></div></body></html>').setTitle('DGL');
}
function acqPubErrorHtml_(lang){var msg=lang==='pt-BR'?'Revise os campos obrigatórios e tente novamente.':lang==='es'?'Revise los campos obligatorios e intente nuevamente.':'Please review the required fields and try again.';return '<!doctype html><html><body style="font-family:Arial;padding:50px"><h2>'+acqPubEsc_(msg)+'</h2></body></html>';}
function acqPubLandingHtml_(lp,query){
  var l=acqPubLabels_(lp.language),url=ScriptApp.getService().getUrl(),service=acqPubEsc_(lp.service||'Inland Freight');
  function h(name,label,type){return '<label><span>'+acqPubEsc_(label)+'</span><input '+(type?'type="'+type+'" ':'')+'name="'+name+'" '+((name==='company'||name==='email')?'required':'')+'></label>';}
  return '<!doctype html><html lang="'+acqPubEsc_(lp.language||'en')+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+acqPubCss_()+'</style></head><body><header><b>DGL</b><span>Dedicated Ground Logistics</span></header><main><section class="hero"><div><small>INLAND FREIGHT BROKER</small><h1>'+acqPubEsc_(lp.headline)+'</h1><p>'+acqPubEsc_(lp.subheadline)+'</p><a href="#lead">'+acqPubEsc_(lp.ctaLabel)+'</a></div><div class="services"><span>FTL</span><span>LTL</span><span>DRAYAGE</span></div></section><section class="value"><b>USA Inland Freight</b><p>FTL · LTL · Drayage · Cross-border support</p></section><section id="lead" class="formwrap"><h2>'+acqPubEsc_(lp.ctaLabel)+'</h2><form method="post" action="'+acqPubEsc_(url)+'"><input type="hidden" name="slug" value="'+acqPubEsc_(lp.slug)+'"><input type="hidden" name="service" value="'+service+'"><input type="hidden" name="utm_source" value="'+acqPubEsc_(query.utm_source||lp.utmSource)+'"><input type="hidden" name="utm_medium" value="'+acqPubEsc_(query.utm_medium||lp.utmMedium)+'"><input type="hidden" name="utm_campaign" value="'+acqPubEsc_(query.utm_campaign||lp.utmCampaign)+'"><input class="trap" name="website" tabindex="-1" autocomplete="off">'+h('firstName',l.firstName)+h('lastName',l.lastName)+h('company',l.company)+h('email',l.email,'email')+h('phone',l.phone,'tel')+h('country',l.country)+h('origin',l.origin)+h('destination',l.destination)+'<label class="full"><span>'+acqPubEsc_(l.notes)+'</span><textarea name="notes"></textarea></label><button type="submit">'+acqPubEsc_(l.submit)+'</button></form></section></main><footer>DGL · Your inland freight partner</footer></body></html>';
}
function acqPubCss_(){return 'body{margin:0;font-family:Arial,sans-serif;color:#101828;background:#fff}header{background:#05035C;color:#fff;padding:20px 6%;border-bottom:4px solid #77B82A}header b{font-size:22px}header span{margin-left:10px;opacity:.78;font-size:12px}.hero{display:grid;grid-template-columns:1.3fr .7fr;gap:40px;padding:70px 6%;background:#f6f8fb}.hero small{color:#5d991e;font-weight:800;letter-spacing:.14em}.hero h1{font-size:48px;line-height:1.03;color:#05035C;max-width:760px;margin:14px 0}.hero p{font-size:18px;line-height:1.55;color:#566171;max-width:700px}.hero a{display:inline-block;margin-top:10px;background:#77B82A;color:#102300;padding:15px 20px;border-radius:8px;font-weight:800;text-decoration:none}.services{display:grid;align-content:center;gap:12px}.services span{background:#05035C;color:#fff;border-radius:10px;padding:18px;text-align:center;font-weight:800}.value{padding:26px 6%;border-top:1px solid #e7eaf0;border-bottom:1px solid #e7eaf0}.value b{color:#05035C;font-size:20px}.value p{color:#667085}.formwrap{padding:55px 6%;max-width:900px;margin:auto}.formwrap h2{color:#05035C}form{display:grid;grid-template-columns:1fr 1fr;gap:15px}label{display:grid;gap:6px}label span{font-size:12px;font-weight:700;color:#475467}input,textarea{border:1px solid #d7dce5;border-radius:8px;padding:12px;font:inherit}.full,button{grid-column:1/-1}textarea{min-height:90px}button{border:0;border-radius:8px;background:#77B82A;padding:15px;font-weight:900;cursor:pointer}.trap{position:absolute;left:-9999px}footer{padding:30px 6%;background:#05035C;color:#fff;text-align:center}@media(max-width:760px){.hero{grid-template-columns:1fr;padding-top:45px}.hero h1{font-size:36px}form{grid-template-columns:1fr}.full,button{grid-column:1}}';}
