// DEV-ONLY visual QA fixture for DGL Growth OS (tools/growth-qa). Never loaded by the product.
// Shapes mirror real backend responses; values are aggregate counts from the 2026-10-07 shadow
// run (no customer names, emails or accounts).
(function (g) {
  g.DGL_GROWTH_QA_FIXTURE = true;
  const A = g.DGL_MARKETING_BACKEND_ADAPTER_V55; if (!A) return;
  const sc = o => Object.assign({ sent: 0, delivered: 0, bounced: 0, failed: 0, replied: 0, opened: null, clicked: null, openRate: null, ctr: null, ctor: null }, o);
  const groups = [["QNB", 243], ["Retention", 66], ["Reactivation", 19], ["Cross-sell", 17]].map(([t, n], i) => ({ groupId: "G" + i, amOwner: "AM " + (i + 1), opportunityType: t, service: ["FTL", "LTL", "Drayage", "Multiservicio"][i], window: "", eligibleAccounts: n, detectedAccounts: n, suppressedAccounts: 0, priority: i + 1, campaignStatus: "OPPORTUNITY DETECTED", nextAction: "Evaluate campaign eligibility" }));
  const task = (t, scope, n) => ({ taskId: "AT:2026-10-07:OPP:" + scope, title: t, scope, kind: "OPPORTUNITY", state: "APPROVAL", policy: "APPROVAL_REQUIRED", approvalId: "AP:" + scope, approvalStatus: "PENDING", nextAction: "Approve once in AURA; the send then runs through the governed flow", decision: { rationale: "Eligible accounts without an open campaign task for this family", dataSource: "MKT_OPPORTUNITIES" }, result: { plan: { recipients: n, eligibleAccounts: n, contacts: { recipients: n, recentlySent: 0, doNotContact: 0, invalid: 0, duplicate: 0 }, languages: { ES: Math.round(n * .6), EN: n - Math.round(n * .6), PT: 0, UNRESOLVED: 0 }, creativeSystem: "editorial-white", angle: "Stay Close" } } });
  const waiting = [task("Quoted Not Booked: 243 eligible accounts", "QNB", 86), task("Retention: 66 eligible accounts", "RETENTION", 16), task("Reactivation: 19 eligible accounts", "REACTIVATION", 19), task("Cross-Sell: 17 eligible accounts", "CROSS_SELL", 6)];
  const bundle = { meta: { backendMs: 980, contract: "AURA_COMMAND_CENTER_V1" }, agent: { commands: ["Run the next reactivation campaign", "Review QNB opportunities", "Prepare the monthly marketing report"], status: { runtime: "ACTIVE", lastRun: { state: "COMPLETED", finishedAt: "2026-10-07T22:51:26Z" } }, priorities: waiting.slice(0, 3), opportunities: waiting, actionQueue: [], waitingApproval: waiting, running: [], blocked: [], completed: [{ taskId: "M1", title: "Measure CMP-CAMPANA-A-HA-PRIORITARIA", scope: "REACTIVATION", state: "COMPLETED", policy: "AUTO" }], nextBestActions: waiting.map(t => ({ title: t.title, nextAction: t.nextAction, state: t.state })), recentResults: [] },
    performance: { summary: { sent: 325, failed: 1, bounced: 0, replied: 2, opened: 2, clicked: 1, sentUniqueEmails: 324, sentUniqueAccounts: 120 }, rows: [], tracking: { opened: "TRACKED" }, scopes: { "CMP-CAMPANA-A-HA-PRIORITARIA": { campaignId: "CMP-CAMPANA-A-HA-PRIORITARIA", currentFamily: "Reactivation", latestRunId: "GL-1", lastSentAt: "2026-10-01", historicalFamilies: { Retention: 109 }, currentRun: sc({ sent: 214, delivered: 214, replied: 2 }), currentFamilyRun: sc({ sent: 214, delivered: 214, replied: 2 }), historical: sc({ sent: 109, delivered: 109 }), allTime: sc({ sent: 323, delivered: 323, replied: 2 }), pipeline: { rfq: 0, quote: 0, load: 0 } } } },
    retention: {}, campanaA: { realSendsDetected: 323 }, execution: { records: [] }, latestRun: null };
  Object.assign(A, { isConnected: () => true, getConnectionState: () => ({ state: "PRIVATE_BACKEND", mode: "PRIVATE_BACKEND", connected: true }),
    v6Opportunities: async () => ({ status: "READY", groups, summary: { totalSignals: 345, eligibleAccounts: 345 } }), v6PipelineSummary: async () => ({}),
    v6AuraCommandCenter: async () => bundle,
    // Synthetic Campaign Studio context (no backend call from the QA page).
    campaignStudioContext: async campaignId => ({ campaignId, campaignName: "Campaña A · HA prioritaria (QA)", campaignType: "Reactivation", objective: "Reactivation", service: "Multiservicio", messageAngle: "", status: "ACTIVE",
      requiredLanguages: ["ES", "EN"], approvedCreativeVariants: {}, missingCreativeVariants: ["ES", "EN"], creativeSetStatus: "PENDING", approvalStatus: "PENDING", audienceResolved: true, testDraftReviewRequired: false, missingTestDrafts: [], approvedCreatives: {}, eligibleContacts: 214, excludedContacts: 0,
      // Synthetic contact record for the personalized preview (QA only; not a real customer).
      previewRecipient: { firstName: "Laura", company: "Empresa Demo QA", source: "contacto sintético de QA" } }),
    getLatestApprovedCreative: async () => null,
    // Synthetic approvals: recorded in memory only; the next Command Center read reflects them.
    agentDecide: async (approvalId, decision) => { bundle.agent.waitingApproval = bundle.agent.waitingApproval.filter(t => t.approvalId !== approvalId); bundle.agent.priorities = bundle.agent.priorities.filter(t => t.approvalId !== approvalId); bundle.agent.opportunities = bundle.agent.opportunities.map(t => t.approvalId === approvalId ? Object.assign({}, t, { approvalStatus: decision, state: decision === "APPROVED" ? "BLOCKED" : "CANCELLED", blockReason: decision === "APPROVED" ? "EXTERNAL_EXECUTION_DISABLED_PHASE_V1" : "" }) : t); g.__qaDecisions = (g.__qaDecisions || []).concat([{ approvalId, decision }]); return { status: "RECORDED" }; },
    // Studio write actions need the real private backend. QA does not simulate them: they fail with
    // an explicit message, no request leaves the page and the connection state is not touched.
    ...Object.fromEntries(["approveCreative", "approveCreativeSet", "campaignStudioTestDraft", "revokeApprovedCreative"].map(k => [k, async () => { throw new Error("QA (datos de prueba): esta acción escribe en el backend privado y aquí no se simula. Para aprobar variantes o crear borradores de prueba, abra /growth/ y conecte el backend privado."); }])),
    agentRunNow: async () => ({ status: "COMPLETED" }), campaignStudioList: async () => ({ campaigns: [{ campaignId: "CMP-CAMPANA-A-HA-PRIORITARIA", campaignName: "Campaña A · HA prioritaria", campaignType: "Reactivation", service: "Multiservicio", status: "ACTIVE" }] }) });
})(window);

document.addEventListener("DOMContentLoaded", () => { const b = document.createElement("div"); b.className = "gos-fixture-banner"; b.textContent = "DATOS DE PRUEBA — esta página usa un fixture de QA, no datos reales. Para datos reales use /growth/ y conecte el backend."; b.style.cssText = "position:fixed;top:0;left:0;right:0;z-index:9999;padding:6px 12px;background:#F5B544;color:#2A1A00;font:700 12px Inter,sans-serif;text-align:center"; document.body.appendChild(b); document.body.style.paddingTop = "28px"; });
