// DEV-ONLY visual QA fixture for DGL Growth OS (tools/growth-qa). Never loaded by the product.
// Shapes mirror real backend responses; values are aggregate counts from the 2026-10-07 shadow
// run (no customer names, emails or accounts).
(function (g) {
  const A = g.DGL_MARKETING_BACKEND_ADAPTER_V55; if (!A) return;
  const sc = o => Object.assign({ sent: 0, delivered: 0, bounced: 0, failed: 0, replied: 0, opened: null, clicked: null, openRate: null, ctr: null, ctor: null }, o);
  const groups = [["QNB", 243], ["Retention", 66], ["Reactivation", 19], ["Cross-sell", 17]].map(([t, n], i) => ({ groupId: "G" + i, amOwner: "AM " + (i + 1), opportunityType: t, service: ["FTL", "LTL", "Drayage", "Multiservicio"][i], window: "", eligibleAccounts: n, detectedAccounts: n, suppressedAccounts: 0, priority: i + 1, campaignStatus: "OPPORTUNITY DETECTED", nextAction: "Evaluate campaign eligibility" }));
  const task = (t, scope, n) => ({ taskId: "AT:2026-10-07:OPP:" + scope, title: t, scope, kind: "OPPORTUNITY", state: "APPROVAL", policy: "APPROVAL_REQUIRED", approvalId: "AP:" + scope, approvalStatus: "PENDING", nextAction: "Approve once in AURA; the send then runs through the governed flow", decision: { rationale: "Eligible accounts without an open campaign task for this family", dataSource: "MKT_OPPORTUNITIES" }, result: { plan: { recipients: n, eligibleAccounts: n, contacts: { recipients: n, recentlySent: 0, doNotContact: 0, invalid: 0, duplicate: 0 }, languages: { ES: Math.round(n * .6), EN: n - Math.round(n * .6), PT: 0, UNRESOLVED: 0 }, creativeSystem: "editorial-white", angle: "Stay Close" } } });
  const waiting = [task("Quoted Not Booked: 243 eligible accounts", "QNB", 86), task("Retention: 66 eligible accounts", "RETENTION", 16), task("Reactivation: 19 eligible accounts", "REACTIVATION", 19), task("Cross-Sell: 17 eligible accounts", "CROSS_SELL", 6)];
  const bundle = { meta: { backendMs: 980, contract: "AURA_COMMAND_CENTER_V1" }, agent: { commands: ["Run the next reactivation campaign", "Review QNB opportunities", "Prepare the monthly marketing report"], status: { runtime: "ACTIVE", lastRun: { state: "COMPLETED", finishedAt: "2026-10-07T22:51:26Z" } }, priorities: waiting.slice(0, 3), opportunities: waiting, actionQueue: [], waitingApproval: waiting, running: [], blocked: [], completed: [{ taskId: "M1", title: "Measure CMP-CAMPANA-A-HA-PRIORITARIA", scope: "REACTIVATION", state: "COMPLETED", policy: "AUTO" }], nextBestActions: waiting.map(t => ({ title: t.title, nextAction: t.nextAction, state: t.state })), recentResults: [] },
    performance: { summary: { sent: 325, failed: 1, bounced: 0, replied: 2, opened: 2, clicked: 1, sentUniqueEmails: 324, sentUniqueAccounts: 120 }, rows: [], tracking: { opened: "TRACKED" }, scopes: { "CMP-CAMPANA-A-HA-PRIORITARIA": { campaignId: "CMP-CAMPANA-A-HA-PRIORITARIA", currentFamily: "Reactivation", latestRunId: "GL-1", lastSentAt: "2026-10-01", historicalFamilies: { Retention: 109 }, currentRun: sc({ sent: 214, delivered: 214, replied: 2 }), currentFamilyRun: sc({ sent: 214, delivered: 214, replied: 2 }), historical: sc({ sent: 109, delivered: 109 }), allTime: sc({ sent: 323, delivered: 323, replied: 2 }), pipeline: { rfq: 0, quote: 0, load: 0 } } } },
    retention: {}, campanaA: { realSendsDetected: 323 }, execution: { records: [] }, latestRun: null };
  Object.assign(A, { isConnected: () => true, getConnectionState: () => ({ state: "PRIVATE_BACKEND", mode: "PRIVATE_BACKEND", connected: true }),
    v6Opportunities: async () => ({ status: "READY", groups, summary: { totalSignals: 345, eligibleAccounts: 345 } }), v6PipelineSummary: async () => ({}),
    v6AuraCommandCenter: async () => bundle, campaignStudioList: async () => ({ campaigns: [{ campaignId: "CMP-CAMPANA-A-HA-PRIORITARIA", campaignName: "Campaña A · HA prioritaria", campaignType: "Reactivation", service: "Multiservicio", status: "ACTIVE" }] }) });
})(window);
