var MKT_V6_PRIORITY={'QNB':1,'QUOTED NOT BOOKED':1,'RETENTION':2,'RETENTION RISK':2,'REACTIVATION':3,'CROSS-SELL':4,'CROSS SELL':4,'NURTURE':5,'RELATIONSHIP RENEWAL':5};
function v6Now_(){return new Date();}
function v6DateValue_(value){if(!value)return null;var d=value instanceof Date?value:new Date(value);return isNaN(d.getTime())?null:d;}
function v6DaysSince_(value,now){var d=v6DateValue_(value);return d?Math.floor((now.getTime()-d.getTime())/86400000):null;}
function v6Priority_(type){return MKT_V6_PRIORITY[String(type||'').trim().toUpperCase()]||99;}
function v6TableHeaders_(name){var s=v6Sheet_(name);if(!s)throw new Error(name+' NOT FOUND');return {sheet:s,headers:s.getRange(1,1,1,s.getLastColumn()).getValues()[0]};}
function v6UpsertByKey_(name,keyFields,record){var t=v6TableHeaders_(name),rows=t.sheet.getLastRow()>1?t.sheet.getRange(2,1,t.sheet.getLastRow()-1,t.headers.length).getValues():[],index=-1;for(var i=0;i<rows.length;i++){var match=true;for(var k=0;k<keyFields.length;k++){var col=t.headers.indexOf(keyFields[k]);if(String(rows[i][col]||'')!==String(record[keyFields[k]]||'')){match=false;break;}}if(match){index=i+2;break;}}var values=t.headers.map(function(h){return record[h]==null?'':record[h];});if(index>0)t.sheet.getRange(index,1,1,values.length).setValues([values]);else t.sheet.appendRow(values);return record;}
function v6FrequencyStatus_(payload){var p=payload||{},accountId=String(p.accountId||'').trim(),contactId=String(p.contactId||'').trim();if(!accountId)return {status:'ACCOUNT SCOPE UNRESOLVED',eligible:false,accountTouches30d:0,contactTouches30d:0,lastMarketingTouchAt:null,cooldownUntil:null,activeCampaignId:null,reason:'ACCOUNT ID REQUIRED',nextEligibleAt:null};if(p.exclusionBlocked===true||p.dnc===true)return {status:'DNC',eligible:false,accountTouches30d:0,contactTouches30d:0,lastMarketingTouchAt:null,cooldownUntil:null,activeCampaignId:null,reason:'EXCLUSION BLOCK',nextEligibleAt:null};
  var now=v6Now_(),rows=v6Rows_('MKT_FREQUENCY_LEDGER').filter(function(r){return String(r.accountId||'')===accountId;}),contactRows=contactId?rows.filter(function(r){return String(r.contactId||'')===contactId;}):[],last=null,cooldown=null,active='',accountTouches=0,contactTouches=0,activeType='';
  rows.forEach(function(r){var touch=v6DateValue_(r.lastMarketingTouchAt),stored=Math.max(0,Number(r.touches30d||0)),derived=touch&&v6DaysSince_(touch,now)<=30?1:0;accountTouches+=Math.max(stored,derived);if(touch&&(!last||touch>last))last=touch;var cd=v6DateValue_(r.cooldownUntil);if(cd&&(!cooldown||cd>cooldown))cooldown=cd;if(r.activeCampaignId){active=String(r.activeCampaignId);activeType=String(r.lastCampaignType||'');}});contactRows.forEach(function(r){var touch=v6DateValue_(r.lastMarketingTouchAt),stored=Math.max(0,Number(r.touches30d||0)),derived=touch&&v6DaysSince_(touch,now)<=30?1:0;contactTouches+=Math.max(stored,derived);});
  var base={accountTouches30d:accountTouches,contactTouches30d:contactTouches,lastMarketingTouchAt:last?last.toISOString():null,cooldownUntil:cooldown?cooldown.toISOString():null,activeCampaignId:active||null,nextEligibleAt:null};if(active&&String(p.campaignId||'')!==active){var higher=v6Priority_(activeType)<=v6Priority_(p.campaignType);return Object.assign(base,{status:higher?'HIGHER PRIORITY':'ACTIVE CAMPAIGN',eligible:false,reason:higher?'HIGHER PRIORITY SIGNAL':'COMPETING ACTIVE CAMPAIGN'});}if(accountTouches>=2||contactId&&contactTouches>=2)return Object.assign(base,{status:'FREQUENCY CAP',eligible:false,reason:accountTouches>=2?'ACCOUNT 30-DAY CAP':'CONTACT 30-DAY CAP',nextEligibleAt:last?new Date(last.getTime()+30*86400000).toISOString():null});
  var signal=v6DateValue_(rows.reduce(function(v,r){var d=v6DateValue_(r.lastCommercialSignalAt);return d&&(!v||d>v)?d:v;},null)),override=!!(p.newCommercialSignalEligible&&signal&&last&&signal>last);if(cooldown&&cooldown>now&&!override)return Object.assign(base,{status:'COOLDOWN',eligible:false,reason:'NO-RESPONSE COOLDOWN',nextEligibleAt:cooldown.toISOString()});var requested=Number(p.followUpDays||0),tooSoon=last&&v6DaysSince_(last,now)<10;if((requested>=3&&requested<=8)||requested===38||tooSoon)return Object.assign(base,{status:'FOLLOW-UP TOO SOON',eligible:false,reason:requested===38?'38-DAY DEFAULT NOT PERMITTED':'MINIMUM 10-DAY SPACING',nextEligibleAt:last?new Date(last.getTime()+10*86400000).toISOString():null});return Object.assign(base,{status:'CLEAR',eligible:true,reason:override?'NEW COMMERCIAL SIGNAL OVERRIDE':'PRESSURE CLEAR'});}
function v6EvaluateCampaignPressure_(payload){return v6FrequencyStatus_(payload);}
function v6RecordMarketingTouch_(payload){var p=payload||{};if(p.isTestDraft===true||String(p.eventType||'').toUpperCase()==='TEST_DRAFT')return {status:'IGNORED TEST DRAFT'};if(!p.accountId||!p.sentAt)throw new Error('REAL PRODUCTION TOUCH REQUIRES accountId AND sentAt');var old=v6Rows_('MKT_FREQUENCY_LEDGER').filter(function(r){return String(r.accountId||'')===String(p.accountId)&&String(r.contactId||'')===String(p.contactId||'');})[0]||{},now=v6Now_(),sent=v6DateValue_(p.sentAt);if(!sent)throw new Error('INVALID sentAt');var t30=v6DaysSince_(old.lastMarketingTouchAt,now)<=30?Number(old.touches30d||0):0,t90=v6DaysSince_(old.lastMarketingTouchAt,now)<=90?Number(old.touches90d||0):0,type=String(p.campaignType||old.lastCampaignType||''),days=Math.min(v6Priority_(type)===5?60:45,Math.max(30,Number(p.cooldownDays||30)));return v6UpsertByKey_('MKT_FREQUENCY_LEDGER',['accountId','contactId'],{accountId:String(p.accountId),contactId:String(p.contactId||''),lastMarketingTouchAt:sent.toISOString(),touches30d:t30+1,touches90d:t90+1,activeCampaignId:String(p.campaignId||''),cooldownUntil:p.campaignCompleted?new Date(sent.getTime()+days*86400000).toISOString():'',lastCampaignType:type,lastResponseAt:old.lastResponseAt||'',lastCommercialSignalAt:p.lastCommercialSignalAt||old.lastCommercialSignalAt||'',frequencyStatus:'CLEAR',updatedAt:now.toISOString()});}
