var MKT_V6_ARCHIVE={root:'1Har0llISmGa4oUDqqcathCXzMZVyyg13',csv:'1wfr_uaQANdksvfIvUILNtQ-dghpQV4QH',html:'1XBX0c9JWQGXy1HZ9e_59wg5bBgqUl85e',copy:'14UmmReyapXX_jmuuNz7M9KcwvwI_OBU8',creative:'1p_8LMks6im0mE_-jx-FdomxKVs4pi9sz',results:'1xnBQCySgQu4eS8A5tTLcMHBXs7DlKiqU'};
var MKT_V6_EXECUTION_CSV_HEADERS=['accountId','contactId','campaignId','executionId','eligibilityStatus','exclusionReason','frequencyStatus','sentStatus','sentAt','sequenceStep','responseStatus','stopped','handoffStatus','rfqId','quoteId','loadId','attributedRevenue'];
function v6CsvEscape_(value){var s=String(value==null?'':value);return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function v6Csv_(headers,rows){return [headers.join(',')].concat((rows||[]).map(function(r){return headers.map(function(h){return v6CsvEscape_(r[h]);}).join(',');})).join('\r\n');}
function v6UpdateExecutionFiles_(executionId,patch){var old=v6ExecutionStatus_({executionId:executionId});if(old.status==='NOT FOUND')throw new Error('EXECUTION NOT FOUND');return v6UpsertByKey_('MKT_CAMPAIGN_EXECUTIONS',['executionId'],Object.assign({},old,patch,{updatedAt:new Date().toISOString()}));}
function v6CreateExecutionCsv_(executionId,rows){if(!Array.isArray(rows)||!rows.length)return {status:'ARCHIVE PENDING',executionCsvDriveFileId:''};var file=DriveApp.getFolderById(MKT_V6_ARCHIVE.csv).createFile(executionId+'.csv',v6Csv_(MKT_V6_EXECUTION_CSV_HEADERS,rows),MimeType.CSV);v6UpdateExecutionFiles_(executionId,{executionCsvDriveFileId:file.getId()});return {status:'CSV ARCHIVED',executionCsvDriveFileId:file.getId()};}
function v6CreateEmailHtmlArchive_(executionId,html){if(!String(html||'').trim())return {status:'ARCHIVE PENDING',emailHtmlDriveFileId:''};var f=DriveApp.getFolderById(MKT_V6_ARCHIVE.html).createFile(executionId+'.html',String(html),MimeType.HTML);v6UpdateExecutionFiles_(executionId,{emailHtmlDriveFileId:f.getId()});return {status:'HTML ARCHIVED',emailHtmlDriveFileId:f.getId()};}
function v6CreateCopyArchive_(executionId,copyPayload){if(!copyPayload||!Object.keys(copyPayload).length)return {status:'ARCHIVE PENDING',copyDriveFileId:''};var f=DriveApp.getFolderById(MKT_V6_ARCHIVE.copy).createFile(executionId+'.json',JSON.stringify(copyPayload,null,2),MimeType.PLAIN_TEXT);v6UpdateExecutionFiles_(executionId,{copyDriveFileId:f.getId()});return {status:'COPY ARCHIVED',copyDriveFileId:f.getId()};}
function v6CreateResultsCsv_(executionId,rows){if(!Array.isArray(rows)||!rows.length)return {status:'RESULTS PENDING',resultsDriveFileId:''};var f=DriveApp.getFolderById(MKT_V6_ARCHIVE.results).createFile(executionId+'-results.csv',v6Csv_(MKT_V6_EXECUTION_CSV_HEADERS,rows),MimeType.CSV);return {status:'RESULTS ARCHIVED',resultsDriveFileId:f.getId()};}
function v6ArchiveExecution_(executionId,payload){var p=payload||{},snapshot=p.audienceSnapshot||p.rows||[],creativeId=String(p.creativeDriveFileId||'');if(creativeId)v6UpdateExecutionFiles_(executionId,{creativeDriveFileId:creativeId});return {csv:v6CreateExecutionCsv_(executionId,snapshot),html:v6CreateEmailHtmlArchive_(executionId,p.finalHtml||''),copy:v6CreateCopyArchive_(executionId,p.copy||{}),creativeDriveFileId:creativeId};}
