var MKT_V6_REPORT_SOURCE_ID='1XPZC_VUPLsmta--MPXi4MHswz9oiYxKbiq58a_khPp4';
var MKT_V6_REPORT_SHEETS=['CUENTAS','FICHA_CLIENTES','LANES_DETALLE','LOADS_ORIGEN_LQ','LQS_SEMANA','LQS_SIN_RESPUESTA','MIGRACION_CAIDAS','MIGRACION_RECUPERADAS'];
var MKT_V6_OPPORTUNITY_PRIORITY={'QNB':1,'RETENTION':2,'REACTIVATION':3,'CROSS-SELL':4,'NURTURE':5};
var MKT_V6_OPPORTUNITY_HEADERS=['opportunityId','accountId','amOwner','opportunityType','service','signalFamily','window','detectedAccounts','eligibleAccounts','suppressedAccounts','eligibilityStatus','suppressionReason','priority','source','sourceSignalId','signalDate','lastEngineRun','nextAction'];

function v6ReportKey_(value){return String(value==null?'':value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'');}
function v6ReportRows_(sheetName){var sheet=SpreadsheetApp.openById(MKT_V6_REPORT_SOURCE_ID).getSheetByName(sheetName);if(!sheet)throw new Error('REPORT SOURCE SHEET NOT FOUND: '+sheetName);var values=sheet.getDataRange().getValues();if(values.length<2)return [];var headers=values.shift().map(v6ReportKey_);return values.filter(function(row){return row.some(function(value){return value!==''&&value!=null;});}).map(function(row){var record={};headers.forEach(function(header,index){record[header]=row[index];});return record;});}
function v6ReportValue_(record,aliases){for(var i=0;i<aliases.length;i++){var key=v6ReportKey_(aliases[i]);if(record[key]!==''&&record[key]!=null)return record[key];}return '';}
function v6AccountId_(record){return String(v6ReportValue_(record,['ACCOUNT_ID','ACCOUNTID','ID_CUENTA','CODIGO_CUENTA','CLIENT_ID','CUSTOMER_ID','CUENTA_ID'])).trim();}
function v6Owner_(record){return String(v6ReportValue_(record,['AM_OWNER','OWNER','ACCOUNT_MANAGER','EJECUTIVO','AM','VENDEDOR'])).trim()||'OWNER REQUIRED';}
function v6Service_(record){return String(v6ReportValue_(record,['SERVICE','SERVICIO','TIPO_SERVICIO','MODE','MODO'])).trim()||'UNSPECIFIED';}
function v6Date_(record){var value=v6ReportValue_(record,['SIGNAL_DATE','FECHA','CREATED_AT','QUOTE_DATE','LQ_DATE','ULTIMA_FECHA','LAST_ACTIVITY']);var date=value instanceof Date?value:new Date(value);return isNaN(date.getTime())?new Date(0):date;}
function v6Bool_(record,aliases){var value=v6ReportKey_(v6ReportValue_(record,aliases));return ['TRUE','YES','SI','1','Y'].indexOf(value)>=0;}
function v6Signal_(type,record,source,extra){var accountId=v6AccountId_(record),now=new Date().toISOString(),status=(extra&&extra.status)||'ELIGIBLE';return {opportunityId:'OPP-'+Utilities.getUuid().slice(0,8).toUpperCase(),accountId:accountId,amOwner:v6Owner_(record),opportunityType:type,service:(extra&&extra.service)||v6Service_(record),signalFamily:(extra&&extra.signalFamily)||type,window:(extra&&extra.window)||'',detectedAccounts:1,eligibleAccounts:status==='ELIGIBLE'?1:0,suppressedAccounts:status==='ELIGIBLE'?0:1,eligibilityStatus:status,suppressionReason:(extra&&extra.reason)||'',priority:MKT_V6_OPPORTUNITY_PRIORITY[type],source:'DGL_REPORT_SOURCE_V6 / '+source,sourceSignalId:String(v6ReportValue_(record,['LQ_ID','QUOTE_ID','LOAD_ID','SIGNAL_ID','ID'])||''),signalDate:v6Date_(record).toISOString(),lastEngineRun:now,nextAction:status==='ELIGIBLE'?'EVALUATE CAMPAIGN PRESSURE':'REVIEW SUPPRESSION'};}
function v6LatestQnbByAccount_(rows){var latest={};rows.forEach(function(row){var accountId=v6AccountId_(row);if(!accountId)return;var current=latest[accountId];if(!current||v6Date_(row).getTime()>v6Date_(current).getTime())latest[accountId]=row;});return latest;}
function v6QnbWindow_(record){var days=Number(v6ReportValue_(record,['DAYS_OLD','DIAS','DAYS_SINCE_QUOTE','AGE_DAYS'])||0);return days<=14?'0-14':days<=30?'15-30':'30+';}
function v6BuildReportSignals_(){var signals=[],qnbRows=v6ReportRows_('LQS_SIN_RESPUESTA').concat(v6ReportRows_('LQS_SEMANA')),latest=v6LatestQnbByAccount_(qnbRows);Object.keys(latest).forEach(function(accountId){var row=latest[accountId];signals.push(v6Signal_('QNB',row,'LQS_SIN_RESPUESTA',{window:v6QnbWindow_(row),signalFamily:'LATEST QNB'}));});
  v6ReportRows_('MIGRACION_CAIDAS').forEach(function(row){if(v6AccountId_(row))signals.push(v6Signal_('RETENTION',row,'MIGRACION_CAIDAS',{signalFamily:'DECLINING ACTIVITY'}));});
  v6ReportRows_('CUENTAS').forEach(function(row){var accountId=v6AccountId_(row);if(!accountId)return;var reason='',status='ELIGIBLE';if(v6Owner_(row)==='OWNER REQUIRED'){status='SUPPRESSED';reason='OWNER REQUIRED';}else if(v6Bool_(row,['COLLECTIONS','COLLECTIONS_BLOCK','BLOQUEO_CARTERA'])){status='SUPPRESSED';reason='COLLECTIONS';}else if(v6Bool_(row,['FALSE_POSITIVE','FALSO_POSITIVO'])){status='SUPPRESSED';reason='FALSE POSITIVE';}signals.push(v6Signal_('REACTIVATION',row,'CUENTAS',{status:status,reason:reason,signalFamily:'DORMANT ACCOUNT'}));});
  v6ReportRows_('FICHA_CLIENTES').forEach(function(row){var accountId=v6AccountId_(row),serviceCount=Number(v6ReportValue_(row,['SERVICE_COUNT','SERVICES_COUNT','NUM_SERVICIOS'])||0),decline=Number(v6ReportValue_(row,['DECLINE_PERCENT','PORCENTAJE_CAIDA','DECLINE_PCT'])||0);if(!accountId||serviceCount!==1)return;signals.push(v6Signal_('CROSS-SELL',row,'FICHA_CLIENTES',{status:decline>20?'SUPPRESSED':'ELIGIBLE',reason:decline>20?'RETENTION PRIORITY':'',signalFamily:'SINGLE SERVICE ACCOUNT'}));});
  v6ReportRows_('MIGRACION_RECUPERADAS').forEach(function(row){if(v6AccountId_(row))signals.push(v6Signal_('NURTURE',row,'MIGRACION_RECUPERADAS',{signalFamily:'RECOVERED ACCOUNT'}));});return signals;}
function v6ApplyReportPriority_(signals){var winner={};signals.forEach(function(signal){var current=winner[signal.accountId];if(signal.eligibilityStatus==='ELIGIBLE'&&(!current||signal.priority<current.priority))winner[signal.accountId]=signal;});signals.forEach(function(signal){var top=winner[signal.accountId];if(top&&top!==signal&&signal.priority>top.priority){signal.eligibilityStatus='SUPPRESSED';signal.suppressionReason='HIGHER PRIORITY SIGNAL';signal.eligibleAccounts=0;signal.suppressedAccounts=1;}});return signals;}
function v6WriteOpportunities_(signals){var sheet=v6Sheet_('MKT_OPPORTUNITIES');if(!sheet)throw new Error('MKT_OPPORTUNITIES NOT FOUND');sheet.clearContents();sheet.getRange(1,1,1,MKT_V6_OPPORTUNITY_HEADERS.length).setValues([MKT_V6_OPPORTUNITY_HEADERS]);if(signals.length)sheet.getRange(2,1,signals.length,MKT_V6_OPPORTUNITY_HEADERS.length).setValues(signals.map(function(signal){return MKT_V6_OPPORTUNITY_HEADERS.map(function(header){return signal[header]==null?'':signal[header];});}));return signals.length;}
function v6RefreshOpportunitiesFromReports_(){MKT_V6_REPORT_SHEETS.forEach(function(name){v6ReportRows_(name);});var signals=v6ApplyReportPriority_(v6BuildReportSignals_()),written=v6WriteOpportunities_(signals);return {status:'REPORT_SOURCE_SYNCED',source:'DGL_REPORT_SOURCE_V6',detected:signals.length,written:written,suppressed:signals.filter(function(x){return x.eligibilityStatus==='SUPPRESSED';}).length,refreshedAt:new Date().toISOString()};}
function v6InstallOpportunityRefreshTrigger_(){ScriptApp.getProjectTriggers().filter(function(trigger){return trigger.getHandlerFunction()==='v6RefreshOpportunitiesFromReports_';}).forEach(function(trigger){ScriptApp.deleteTrigger(trigger);});ScriptApp.newTrigger('v6RefreshOpportunitiesFromReports_').timeBased().everyHours(6).create();return {status:'SIX_HOUR_REPORT_REFRESH_INSTALLED'};}
