var MKT_V6_CONTACT_RECIPIENT_SCHEMA={
  MKT_ACCOUNTS:['accountId','externalSystem','externalAccountId','salesforceAccountId','accountName','amOwner','status','sourceUpdatedAt','createdAt','updatedAt'],
  MKT_CONTACTS_SECURE:['contactId','accountId','externalSystem','externalContactId','salesforceContactId','email','emailStatus','doNotContact','status','sourceUpdatedAt','createdAt','updatedAt'],
  MKT_CAMPAIGN_SCOPES:['scopeId','audienceId','campaignId','campaignType','opportunityType','updatedAt'],
  MKT_SCOPE_ACCOUNTS:['scopeId','audienceId','campaignId','accountId','eligibilityStatus','updatedAt'],
  MKT_EXCLUSIONS:['exclusionId','accountId','contactId','status','active','reasonCode','expiresAt','updatedAt'],
  MKT_AUDIENCES:['audienceRecipientId','recordType','campaignId','scopeId','accountId','contactId','email','eligibilityStatus','exclusionReason','frequencyStatus','audienceResolved','audienceStatus','eligibleContactCount','excludedContactCount','reasonCode','exclusionStatus','exclusionsCleared','resolvedAt','updatedAt']
};
function v6SchemaHeaders_(sheet){if(!sheet)return [];var columns=Number(sheet.getLastColumn()||0);if(columns<1)return [];return sheet.getRange(1,1,1,columns).getValues()[0].map(function(value){return String(value||'').trim();}).filter(function(value){return value!=='';});}
function v6AuditContactRecipientSchema_(){
  var tables={},missingTableCount=0,missingColumnCount=0;Object.keys(MKT_V6_CONTACT_RECIPIENT_SCHEMA).forEach(function(name){var sheet=v6Sheet_(name),headers=v6SchemaHeaders_(sheet),required=MKT_V6_CONTACT_RECIPIENT_SCHEMA[name],missing=required.filter(function(header){return headers.indexOf(header)<0;}),present=required.filter(function(header){return headers.indexOf(header)>=0;});if(!sheet)missingTableCount++;missingColumnCount+=missing.length;tables[name]={sheetPresent:!!sheet,existingColumnCount:headers.length,requiredColumnCount:required.length,presentColumns:present,missingColumns:missing};});return {status:missingTableCount||missingColumnCount?'SCHEMA MIGRATION REQUIRED':'SCHEMA READY',tableCount:Object.keys(tables).length,missingTableCount:missingTableCount,missingColumnCount:missingColumnCount,tables:tables};
}
function v6EnsureContactRecipientSchema_(){
  var before=v6AuditContactRecipientSchema_(),columnsAdded=0,tablesUpdated=0;Object.keys(MKT_V6_CONTACT_RECIPIENT_SCHEMA).forEach(function(name){var state=before.tables[name],sheet=v6Sheet_(name);if(!sheet)throw new Error('SCHEMA MIGRATION REQUIRED: '+name+' NOT FOUND');if(!state.missingColumns.length)return;var start=Math.max(1,Number(sheet.getLastColumn()||0)+1);sheet.getRange(1,start,1,state.missingColumns.length).setValues([state.missingColumns]);columnsAdded+=state.missingColumns.length;tablesUpdated++;});var after=v6AuditContactRecipientSchema_();return {status:after.status,tableCount:after.tableCount,tablesUpdated:tablesUpdated,columnsAdded:columnsAdded,missingTableCount:after.missingTableCount,missingColumnCount:after.missingColumnCount,tables:after.tables};
}
function v6RequireContactRecipientHeaders_(name,required){var sheet=v6Sheet_(name);if(!sheet)throw new Error('SCHEMA MIGRATION REQUIRED: '+name+' NOT FOUND');var headers=v6SchemaHeaders_(sheet),expected=required&&required.length?required:(MKT_V6_CONTACT_RECIPIENT_SCHEMA[name]||[]),missing=expected.filter(function(header){return headers.indexOf(header)<0;});if(missing.length)throw new Error('SCHEMA MIGRATION REQUIRED: '+name+' MISSING '+missing.join(','));return true;}
