// AURA server-side email generation -- Existing Account Growth.
//
// Ports the SAME approved copy strategy already used by Campaign Studio
// (assets/js/copy-engine-v5.js / creative-library-v5.js) so automatic
// campaigns get real, on-brand subject/body/HTML without a human opening
// Campaign Studio. This file introduces NO new marketing strategy -- every
// content block below is copied verbatim from the client-side engine and
// MUST be kept in sync with it. The default angle per objective and the
// default language ('es', matching Campaign Studio's own default when no
// human choice exists) mirror exactly what Campaign Studio itself falls
// back to for an unconfigured campaign.

var MKT_V6_AURA_COPY_SERVICE_PROOF = {
  FTL: ["53' Dry Van", "Nationwide Capacity", "Bilingual Support"],
  LTL: ["LTL Coverage", "Shipment Visibility", "Operational Support"],
  Drayage: ["Port-to-Inland", "Container Drayage", "Major U.S. Ports"],
  "Cross Border": ["Cross-Border Coordination", "Inland Capacity", "Bilingual Support"],
  Reefer: ["Reefer Capacity", "Produce & Food", "Operational Visibility"],
  Intermodal: ["Intermodal Options", "Rail & Inland", "Network Coverage"],
  Multiservicio: ["FTL", "LTL", "Drayage"]
};
var MKT_V6_AURA_CTA = {
  "Generate Quote": { es: "ENVIAR MOVIMIENTO", en: "SEND A SHIPMENT", pt: "ENVIAR EMBARQUE" },
  "Recover Quote": { es: "ACTUALIZAR COTIZACIÓN", en: "UPDATE QUOTE", pt: "ATUALIZAR COTAÇÃO" },
  "Reply": { es: "RESPONDER A DGL", en: "REPLY TO DGL", pt: "RESPONDER À DGL" },
  "Meeting": { es: "AGENDAR CONVERSACIÓN", en: "SCHEDULE A CONVERSATION", pt: "AGENDAR CONVERSA" },
  "Review Service": { es: "REVISAR SERVICIO", en: "REVIEW SERVICE", pt: "REVISAR SERVIÇO" }
};

function v6AuraCopyLanguage_(s) {
  var v = String((s && s.language) || '');
  return v === 'English' || v === 'en' ? 'en' : (v === 'pt-BR' || v === 'Português (Brasil)' || v === 'pt' ? 'pt' : 'es');
}
function v6AuraCopyCta_(objective, angle, lg, ctaIntent) {
  if (objective === 'Cross-Sell') {
    var byAngle = { "Additional Capability": { es: "REVISAR CAPACIDAD", en: "REVIEW CAPACITY", pt: "REVISAR CAPACIDADE" }, "One Partner": { es: "VER OPCIONES", en: "SEE OPTIONS", pt: "VER OPÇÕES" }, "Service Expansion": { es: "ENVIAR MOVIMIENTO", en: "SEND A SHIPMENT", pt: "ENVIAR EMBARQUE" } };
    if (byAngle[angle]) return byAngle[angle][lg];
  }
  var c = MKT_V6_AURA_CTA[ctaIntent] || MKT_V6_AURA_CTA["Generate Quote"];
  return c[lg] || c.es;
}

function v6AuraCopyQnb_(lg, service, window) {
  var w = window || '0-14';
  if (lg === 'en') {
    if (w === '30+') return { subjectA: '{{firstName}}, should we reopen this ' + service + ' requirement?', subjectB: '{{firstName}}, any update on this previous quote?', preheader: 'If the requirement changed, we can build a fresh quote around the current movement.', headline: 'SHOULD WE REOPEN IT?', body: 'We quoted a ' + service + ' movement for {{company}} some time ago and wanted to check whether a similar requirement is still on your radar.', body2: 'If the dates, lane or conditions changed, send the current details and we can start from there.' };
    if (w === '15-30') return { subjectA: '{{firstName}}, is this ' + service + ' requirement still moving?', subjectB: '{{firstName}}, should we update this quote?', preheader: 'We can review the quote again if dates or requirements changed.', headline: 'DOES THIS STILL NEED COVERAGE?', body: 'I wanted to check whether the ' + service + ' movement we quoted for {{company}} is still in process.', body2: 'If the date, lane or any requirement changed, send the update and we will review it again.' };
    return { subjectA: '{{firstName}}, is this ' + service + ' move still active?', subjectB: '{{firstName}}, should we revisit this quote?', preheader: 'We can review the movement again if dates or requirements changed.', headline: 'STILL ACTIVE?', body: 'I wanted to confirm whether the ' + service + ' movement we quoted for {{company}} is still in process.', body2: 'If the date, origin, destination or any requirement changed, send the update and we can review it again.' };
  }
  if (lg === 'pt') {
    if (w === '30+') return { subjectA: '{{firstName}}, retomamos esse requerimento de ' + service + '?', subjectB: '{{firstName}}, alguma novidade sobre essa cotação?', preheader: 'Se o requerimento mudou, podemos preparar uma nova cotação com as informações atuais.', headline: 'VAMOS RETOMAR?', body: 'Cotamos um embarque ' + service + ' para {{company}} há algum tempo e queria confirmar se ainda existe uma necessidade parecida em andamento.', body2: 'Se a data, a rota ou as condições mudaram, me envie as informações atuais que revisamos a partir daí.' };
    if (w === '15-30') return { subjectA: '{{firstName}}, esse requerimento de ' + service + ' ainda está em andamento?', subjectB: '{{firstName}}, atualizamos essa cotação?', preheader: 'Podemos revisar novamente a tarifa se a data ou o requerimento mudaram.', headline: 'AINDA PRECISA DE COBERTURA?', body: 'Queria confirmar se o embarque ' + service + ' que cotamos para {{company}} ainda está em processo.', body2: 'Se a data, a rota ou alguma condição mudou, me envie a atualização que revisamos novamente.' };
    return { subjectA: '{{firstName}}, esse embarque ' + service + ' ainda está ativo?', subjectB: '{{firstName}}, revisamos essa cotação novamente?', preheader: 'Podemos revisar o embarque novamente se a data ou o requerimento mudaram.', headline: 'AINDA ESTÁ ATIVO?', body: 'Queria confirmar se o embarque ' + service + ' que cotamos para {{company}} ainda está em processo.', body2: 'Se a data, origem, destino ou alguma condição mudou, me envie a atualização que revisamos novamente.' };
  }
  if (w === '30+') return { subjectA: '{{firstName}}, ¿retomamos este requerimiento ' + service + '?', subjectB: '{{firstName}}, ¿hay alguna actualización sobre esta cotización?', preheader: 'Si el requerimiento cambió, podemos preparar una nueva cotización con la información actual.', headline: '¿LO RETOMAMOS?', body: 'Hace un tiempo cotizamos un movimiento ' + service + ' para {{company}} y quería validar si todavía tienen una necesidad similar en curso.', body2: 'Si cambiaron las fechas, la ruta o las condiciones, envíeme la información actual y lo revisamos desde ahí.' };
  if (w === '15-30') return { subjectA: '{{firstName}}, ¿este requerimiento ' + service + ' sigue en movimiento?', subjectB: '{{firstName}}, ¿actualizamos esta cotización?', preheader: 'Podemos revisar nuevamente la tarifa si cambió la fecha o el requerimiento.', headline: '¿TODAVÍA NECESITAN COBERTURA?', body: 'Quería validar si el movimiento ' + service + ' que cotizamos para {{company}} todavía sigue en proceso.', body2: 'Si cambió la fecha, la ruta o alguna condición, envíeme la actualización y lo revisamos nuevamente.' };
  return { subjectA: '{{firstName}}, ¿sigue activo este movimiento ' + service + '?', subjectB: '{{firstName}}, ¿revisamos nuevamente esta cotización?', preheader: 'Podemos revisar el movimiento nuevamente si cambió la fecha o el requerimiento.', headline: '¿SIGUE ACTIVO?', body: 'Quería confirmar si el movimiento ' + service + ' que cotizamos para {{company}} todavía sigue en proceso.', body2: 'Si cambió la fecha, origen, destino o alguna condición, envíemela y lo revisamos nuevamente.' };
}
var MKT_V6_AURA_RETENTION = {
  "Stay Close": { en: { subjectA: "{{firstName}}, staying close to {{company}}'s operation", subjectB: "{{firstName}}, DGL remains available for {{service}}", preheader: "DGL remains close and available for upcoming transportation needs.", headline: "STAYING CLOSE TO YOUR OPERATION.", body: "We want to stay close to {{company}}'s transportation needs and remain available for upcoming {{service}} requirements.", body2: "If a new lane, volume change or movement comes up, our team is ready to review it with you." }, es: { subjectA: "{{firstName}}, seguimos cerca de la operación de {{company}}", subjectB: "{{firstName}}, DGL sigue disponible para {{service}}", preheader: "DGL sigue cerca y disponible para sus próximos requerimientos de transporte.", headline: "SEGUIMOS CERCA DE SU OPERACIÓN.", body: "Queremos mantenernos cerca de las necesidades de transporte de {{company}} y disponibles para sus próximos requerimientos {{service}}.", body2: "Si surge una nueva ruta, un cambio de volumen o un próximo movimiento, nuestro equipo está listo para revisarlo con ustedes." }, pt: { subjectA: "{{firstName}}, seguimos próximos da operação da {{company}}", subjectB: "{{firstName}}, a DGL segue disponível para {{service}}", preheader: "A DGL segue próxima e disponível para as próximas necessidades de transporte.", headline: "PRÓXIMOS DA SUA OPERAÇÃO.", body: "Queremos continuar próximos das necessidades de transporte da {{company}} e disponíveis para os próximos requerimentos de {{service}}.", body2: "Se surgir uma nova rota, mudança de volume ou próximo embarque, nossa equipe está pronta para revisar com vocês." } },
  "Planning Ahead": { en: { subjectA: "{{firstName}}, let's plan {{company}}'s next move", subjectB: "Planning ahead for your next {{service}} requirement", preheader: "A quick planning conversation can help prepare capacity for what is next.", headline: "LET'S PLAN THE NEXT MOVE.", body: "Planning ahead gives {{company}} more time to align requirements, timing and {{service}} capacity.", body2: "Share what is coming up and we can review the lane, schedule and operating details together." }, es: { subjectA: "{{firstName}}, planifiquemos el próximo movimiento de {{company}}", subjectB: "Planificación para su próximo requerimiento {{service}}", preheader: "Una conversación anticipada ayuda a preparar capacidad para lo que sigue.", headline: "PLANIFIQUEMOS EL PRÓXIMO MOVIMIENTO.", body: "Planificar con anticipación le da a {{company}} más tiempo para alinear requerimientos, fechas y capacidad {{service}}.", body2: "Compártanos lo que viene y revisamos juntos la ruta, el calendario y los detalles operativos." }, pt: { subjectA: "{{firstName}}, vamos planejar o próximo embarque da {{company}}", subjectB: "Planejamento para o próximo requerimento de {{service}}", preheader: "Uma conversa antecipada ajuda a preparar capacidade para o que vem a seguir.", headline: "VAMOS PLANEJAR O PRÓXIMO EMBARQUE.", body: "Planejar com antecedência dá à {{company}} mais tempo para alinhar requerimentos, prazos e capacidade de {{service}}.", body2: "Compartilhe o que está por vir e revisamos juntos a rota, o cronograma e os detalhes operacionais." } },
  "Relationship Continuity": { en: { subjectA: "{{firstName}}, continuity for what comes next", subjectB: "{{company}} | keeping the operation moving", preheader: "DGL remains ready to support continuity across upcoming ground movements.", headline: "CONTINUITY FOR WHAT COMES NEXT.", body: "Our relationship with {{company}} gives us a strong foundation to support continuity across upcoming {{service}} movements.", body2: "When the next requirement is ready, send the details and we will help keep the operation moving." }, es: { subjectA: "{{firstName}}, continuidad para lo que sigue", subjectB: "{{company}} | mantengamos la operación en movimiento", preheader: "DGL sigue disponible para dar continuidad a sus próximos movimientos terrestres.", headline: "CONTINUIDAD PARA LO QUE SIGUE.", body: "Nuestra relación con {{company}} nos da una base sólida para apoyar la continuidad de sus próximos movimientos {{service}}.", body2: "Cuando esté listo el siguiente requerimiento, envíenos los detalles y ayudamos a mantener la operación en movimiento." }, pt: { subjectA: "{{firstName}}, continuidade para o que vem a seguir", subjectB: "{{company}} | mantendo a operação em movimento", preheader: "A DGL segue pronta para apoiar a continuidade dos próximos embarques terrestres.", headline: "CONTINUIDADE PARA O QUE VEM A SEGUIR.", body: "Nosso relacionamento com a {{company}} nos dá uma base sólida para apoiar a continuidade dos próximos embarques de {{service}}.", body2: "Quando o próximo requerimento estiver pronto, envie os detalhes e ajudamos a manter a operação em movimento." } }
};
var MKT_V6_AURA_CROSS_SELL = {
  "Additional Capability": { en: { subjectA: "{{firstName}}, an additional capability for {{company}}", subjectB: "{{company}} | expand your options with {{service}}", preheader: "An additional DGL option to complement your current operation.", headline: "ONE MORE OPTION FOR YOUR OPERATION.", body: "In addition to the services {{company}} already uses with DGL, we want to make our {{service}} capacity available when your team needs another option.", body2: "If you have an upcoming lane or requirement where it could fit, send us the details and we will review capacity." }, es: { subjectA: "{{firstName}}, una capacidad adicional para {{company}}", subjectB: "{{company}} | ampliemos sus opciones con {{service}}", preheader: "Una alternativa adicional de DGL para complementar su operación actual.", headline: "UNA CAPACIDAD MÁS PARA SU OPERACIÓN.", body: "Además de los servicios que {{company}} ya trabaja con DGL, queremos poner a su disposición nuestra capacidad {{service}} para movimientos donde necesiten una alternativa adicional.", body2: "Si tienen una ruta o requerimiento próximo donde pueda encajar, compártanos los detalles y revisamos capacidad." }, pt: { subjectA: "{{firstName}}, uma capacidade adicional para a {{company}}", subjectB: "{{company}} | amplie suas opções com {{service}}", preheader: "Uma alternativa adicional da DGL para complementar sua operação atual.", headline: "MAIS UMA OPÇÃO PARA SUA OPERAÇÃO.", body: "Além dos serviços que a {{company}} já utiliza com a DGL, queremos disponibilizar nossa capacidade de {{service}} para embarques onde precisem de uma alternativa adicional.", body2: "Se tiverem uma rota ou requerimento próximo onde possa se encaixar, compartilhe os detalhes e revisamos a capacidade." } },
  "One Partner": { en: { subjectA: "{{firstName}}, more ground options through one DGL relationship", subjectB: "{{company}} | one partner, more options", preheader: "Access another DGL ground service through the commercial relationship you already know.", headline: "MORE OPTIONS. ONE PARTNER.", body: "DGL can give {{company}} one commercial point of access to an additional {{service}} option while complementing the transportation resources you already use.", body2: "If you would like to review where this capability could support your operation, we can walk through the available options." }, es: { subjectA: "{{firstName}}, más opciones desde una sola relación con DGL", subjectB: "{{company}} | un solo partner, más opciones", preheader: "Acceda a un servicio terrestre adicional desde la relación comercial que ya tiene con DGL.", headline: "MÁS OPCIONES. UN SOLO PARTNER.", body: "DGL puede ofrecerle a {{company}} un solo punto de acceso comercial a una opción adicional de {{service}}, complementando los recursos de transporte que ya utiliza.", body2: "Si desea revisar dónde puede apoyar esta capacidad a su operación, podemos conversar sobre las opciones disponibles." }, pt: { subjectA: "{{firstName}}, mais opções terrestres em um só relacionamento com a DGL", subjectB: "{{company}} | um parceiro, mais opções", preheader: "Acesse mais um serviço terrestre da DGL a partir do relacionamento comercial que vocês já têm.", headline: "MAIS OPÇÕES. UM SÓ PARCEIRO.", body: "A DGL pode oferecer à {{company}} um único ponto de acesso comercial a mais uma opção de {{service}}, complementando os recursos de transporte que já utilizam.", body2: "Se quiser revisar onde essa capacidade pode apoiar sua operação, podemos conversar sobre as opções disponíveis." } },
  "Service Expansion": { en: { subjectA: "{{firstName}}, let's expand what DGL moves with {{company}}", subjectB: "{{company}} | add {{service}} to our work together", preheader: "Build on the DGL relationship already supporting your operation.", headline: "LET'S EXPAND WHAT WE ALREADY MOVE TOGETHER.", body: "The work DGL already does with {{company}} gives us a practical starting point to introduce our {{service}} capability.", body2: "Send us an upcoming movement and we will review how this service can fit into the operation we already support together." }, es: { subjectA: "{{firstName}}, ampliemos lo que DGL mueve con {{company}}", subjectB: "{{company}} | sumemos {{service}} a nuestro trabajo conjunto", preheader: "Aprovechemos la relación con DGL que ya apoya su operación.", headline: "AMPLIEMOS LO QUE YA MOVEMOS JUNTOS.", body: "El trabajo que DGL ya realiza con {{company}} nos da un punto de partida práctico para presentar nuestra capacidad {{service}}.", body2: "Envíenos un próximo movimiento y revisamos cómo puede integrarse este servicio a la operación que ya apoyamos juntos." }, pt: { subjectA: "{{firstName}}, vamos ampliar o que a DGL movimenta com a {{company}}", subjectB: "{{company}} | inclua {{service}} no nosso trabalho conjunto", preheader: "Vamos construir sobre o relacionamento com a DGL que já apoia sua operação.", headline: "VAMOS AMPLIAR O QUE JÁ MOVIMENTAMOS JUNTOS.", body: "O trabalho que a DGL já realiza com a {{company}} nos dá um ponto de partida prático para apresentar nossa capacidade de {{service}}.", body2: "Envie um próximo embarque e revisamos como esse serviço pode se integrar à operação que já apoiamos juntos." } }
};
var MKT_V6_AURA_REACTIVATION = {
  "Previous Relationship": { en: { subjectA: "{{firstName}}, any {{service}} moves coming up?", subjectB: "{{firstName}}, DGL is ready for your next {{service}} move", preheader: "We are available to review your next ground transportation requirements.", headline: "LET'S MOVE AGAIN.", body: "We previously had the opportunity to support {{company}} and wanted to put DGL back at your disposal for upcoming {{service}} moves.", body2: "If you have anything to quote or schedule, send it over and we will review capacity and pricing." }, es: { subjectA: "{{firstName}}, ¿tienen movimientos {{service}} próximos?", subjectB: "{{firstName}}, DGL está disponible para su próximo movimiento {{service}}", preheader: "Estamos disponibles para revisar sus próximos requerimientos terrestres.", headline: "VOLVAMOS A MOVER CARGA.", body: "Hace un tiempo tuvimos la oportunidad de apoyar a {{company}} y quería volver a poner a DGL a su disposición para sus próximos movimientos {{service}}.", body2: "Si tienen algo por cotizar o programar, envíemelo y revisamos capacidad y tarifa." }, pt: { subjectA: "{{firstName}}, têm embarques de {{service}} previstos?", subjectB: "{{firstName}}, a DGL está pronta para seu próximo embarque {{service}}", preheader: "Estamos disponíveis para revisar seus próximos requerimentos terrestres.", headline: "VAMOS VOLTAR A MOVIMENTAR CARGA.", body: "Tivemos a oportunidade de apoiar a {{company}} anteriormente e queria colocar a DGL à disposição novamente para os próximos embarques de {{service}}.", body2: "Se tiverem algo para cotar ou programar, envie que revisamos capacidade e tarifa." } },
  "Ready to Quote": { en: { subjectA: "{{firstName}}, have a {{service}} shipment coming up?", subjectB: "{{firstName}}, send DGL your next movement", preheader: "Send the next requirement and we will review capacity and pricing.", headline: "HAVE A SHIPMENT COMING UP?", body: "DGL is available to review the next {{service}} movement for {{company}} and coordinate the right ground option.", body2: "Send the lane, dates and equipment requirements and we will prepare the next step." }, es: { subjectA: "{{firstName}}, ¿tiene un movimiento {{service}} en puerta?", subjectB: "{{firstName}}, envíe a DGL su próximo movimiento", preheader: "Envíenos el próximo requerimiento y revisamos capacidad y tarifa.", headline: "¿TIENE UN MOVIMIENTO EN PUERTA?", body: "DGL está disponible para revisar el próximo movimiento {{service}} de {{company}} y coordinar la alternativa terrestre adecuada.", body2: "Envíenos la ruta, las fechas y los requerimientos de equipo para preparar el siguiente paso." }, pt: { subjectA: "{{firstName}}, tem um embarque {{service}} chegando?", subjectB: "{{firstName}}, envie à DGL seu próximo embarque", preheader: "Envie o próximo requerimento e revisamos capacidade e tarifa.", headline: "TEM UM EMBARQUE CHEGANDO?", body: "A DGL está disponível para revisar o próximo embarque de {{service}} da {{company}} e coordenar a alternativa terrestre adequada.", body2: "Envie a rota, as datas e os requerimentos de equipamento para prepararmos o próximo passo." } },
  "Service Reminder": { en: { subjectA: "{{firstName}}, DGL remains available for {{service}}", subjectB: "{{company}} | {{service}} support from DGL", preheader: "DGL remains available for upcoming {{service}} requirements.", headline: "DGL IS STILL AVAILABLE FOR YOUR {{service}} MOVES.", body: "DGL remains available to support {{company}} with upcoming {{service}} movements and coordinated ground capacity.", body2: "When a requirement comes up, send the details and we will review coverage, timing and pricing." }, es: { subjectA: "{{firstName}}, DGL sigue disponible para {{service}}", subjectB: "{{company}} | apoyo {{service}} de DGL", preheader: "DGL sigue disponible para sus próximos requerimientos {{service}}.", headline: "DGL SIGUE DISPONIBLE PARA SUS MOVIMIENTOS {{service}}.", body: "DGL sigue disponible para apoyar a {{company}} con próximos movimientos {{service}} y capacidad terrestre coordinada.", body2: "Cuando surja un requerimiento, envíenos los detalles y revisamos cobertura, fechas y tarifa." }, pt: { subjectA: "{{firstName}}, a DGL segue disponível para {{service}}", subjectB: "{{company}} | apoio em {{service}} da DGL", preheader: "A DGL segue disponível para os próximos requerimentos de {{service}}.", headline: "A DGL SEGUE DISPONÍVEL PARA SEUS EMBARQUES DE {{service}}.", body: "A DGL segue disponível para apoiar a {{company}} com os próximos embarques de {{service}} e capacidade terrestre coordenada.", body2: "Quando surgir um requerimento, envie os detalhes e revisamos cobertura, prazos e tarifa." } }
};
var MKT_V6_AURA_DEFAULT_ANGLE = { RETENTION: 'Stay Close', 'CROSS-SELL': 'Additional Capability', REACTIVATION: 'Previous Relationship' };

function v6AuraGenerateCopy_(scope, campaign) {
  var lg = v6AuraCopyLanguage_(campaign), service = campaign.service || 'Multiservicio', objective = campaign.objective;
  var x;
  if (objective === 'Quoted Not Booked') x = v6AuraCopyQnb_(lg, service, scope.window);
  else if (objective === 'Retention') x = (MKT_V6_AURA_RETENTION[MKT_V6_AURA_DEFAULT_ANGLE.RETENTION])[lg];
  else if (objective === 'Cross-Sell') x = (MKT_V6_AURA_CROSS_SELL[MKT_V6_AURA_DEFAULT_ANGLE['CROSS-SELL']])[lg];
  else x = (MKT_V6_AURA_REACTIVATION[MKT_V6_AURA_DEFAULT_ANGLE.REACTIVATION])[lg];
  var angle = objective === 'Retention' ? MKT_V6_AURA_DEFAULT_ANGLE.RETENTION : objective === 'Cross-Sell' ? MKT_V6_AURA_DEFAULT_ANGLE['CROSS-SELL'] : objective === 'Reactivation' ? MKT_V6_AURA_DEFAULT_ANGLE.REACTIVATION : '';
  var cta = v6AuraCopyCta_(objective, angle, lg, 'Generate Quote');
  return { subjectA: x.subjectA, subjectB: x.subjectB, preheader: x.preheader, headline: x.headline, body: x.body, body2: x.body2, cta: cta, language: lg, angle: angle };
}

function v6AuraEsc_(v) { return String(v == null ? '' : v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
// firstName is optional (4th arg) and defaults to 'Team' -- byte-identical to the original
// behavior for every existing caller that only ever passed (text, company, service). Added so
// MarketingV6AuraEmailDispatcher.gs can merge a REAL contact firstName into the same approved
// copy instead of duplicating this token-replacement logic.
function v6AuraSample_(text, company, service, firstName) {
  return String(text || '').replace(/\{\{firstName\}\}/g, firstName || 'Team').replace(/\{\{company\}\}/g, company || 'your company').replace(/\{\{service\}\}/g, service || 'freight');
}
// vars (3rd arg) is optional and defaults to the exact same sample values used before this
// parameter existed (campaign.campaignName/amOwner as company, 'Team' as firstName) -- every
// existing 2-arg call (the scope-level copy archive) is unaffected. When the dispatcher passes
// real {firstName, company, service}, the SAME brand template renders a genuinely personalized,
// per-recipient email instead of a generic sample.
function v6AuraEmailHtml_(campaign, copy, vars) {
  var e = v6AuraEsc_, v = vars || {};
  var company = v.company || campaign.campaignName || campaign.amOwner || 'your company', service = v.service || campaign.service || 'Multiservicio', firstName = v.firstName || 'Team';
  var proof = MKT_V6_AURA_COPY_SERVICE_PROOF[service] || MKT_V6_AURA_COPY_SERVICE_PROOF.Multiservicio;
  var h = v6AuraSample_(copy.headline, company, service, firstName), b = v6AuraSample_(copy.body, company, service, firstName), b2 = v6AuraSample_(copy.body2, company, service, firstName), pre = v6AuraSample_(copy.preheader, company, service, firstName);
  var proofRow = proof.map(function (p) { return '<td style="padding:0 16px 0 0;font-family:Arial,sans-serif"><div style="width:18px;height:2px;background:#77B82A;margin-bottom:7px"></div><div style="font-size:9px;font-weight:800;line-height:1.35;color:#526071">' + e(p) + '</div></td>'; }).join('');
  var button = '<table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#77B82A" style="border-radius:7px"><a href="#" style="display:inline-block;padding:14px 21px;font-family:Arial,sans-serif;font-size:12px;font-weight:900;color:#071005;text-decoration:none">' + e(copy.cta) + ' &rarr;</a></td></tr></table>';
  return '<!doctype html><html><body style="margin:0;background:#F4F5F7">'
    + '<div style="display:none;max-height:0;overflow:hidden">' + e(pre) + '</div>'
    + '<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:34px 12px">'
    + '<table role="presentation" width="620" style="width:100%;max-width:620px;background:#fff;border:1px solid #E5E7EB;border-radius:14px">'
    + '<tr><td style="padding:0"><div style="min-height:72px;display:flex;align-items:center;padding:0 34px;background:#05035C;border-bottom:4px solid #77B82A"><span style="font-family:\'Poppins\',Arial,sans-serif;color:#fff;font-weight:800;font-size:18px">DGL</span></div></td></tr>'
    + '<tr><td style="padding:18px 34px 24px;font-family:Arial,sans-serif">'
    + '<div style="font-size:9px;color:#77B82A;font-weight:900;letter-spacing:1.4px;font-family:\'Poppins\',Arial,sans-serif">' + e(campaign.objective || '') + ' &middot; ' + e(service) + '</div>'
    + '<div style="font-size:30px;line-height:1.1;font-weight:900;color:#05035C;margin-top:13px;font-family:\'Poppins\',Arial,sans-serif">' + e(h) + '</div>'
    + '<p style="font-size:15px;line-height:1.7;color:#4F5868;margin:20px 0 0">' + e(b) + '</p>'
    + '<p style="font-size:15px;line-height:1.7;color:#4F5868;margin:8px 0 22px">' + e(b2) + '</p>' + button
    + '</td></tr>'
    + '<tr><td style="border-top:1px solid #E7E9ED;padding:16px 34px"><table role="presentation"><tr>' + proofRow + '</tr></table></td></tr>'
    + '<tr><td style="border-top:1px solid #E7E9ED;padding:16px 34px;font-family:Arial,sans-serif;font-size:10px;color:#98A2B3">DGL Freight Broker &middot; Your inland freight partner.</td></tr>'
    + '</table></td></tr></table></body></html>';
}

function v6AuraGenerateAndArchiveEmail_(scope, campaign, executionId) {
  var copy = v6AuraGenerateCopy_(scope, campaign);
  var html = v6AuraEmailHtml_(campaign, copy);
  var copyResult = v6CreateCopyArchive_(executionId, { subjectA: copy.subjectA, subjectB: copy.subjectB, preheader: copy.preheader, headline: copy.headline, body: copy.body, body2: copy.body2, cta: copy.cta, language: copy.language, angle: copy.angle, campaignId: campaign.campaignId, generatedAt: v6AuraNow_() });
  var htmlResult = v6CreateEmailHtmlArchive_(executionId, html);
  return { copy: copy, copyArchive: copyResult, htmlArchive: htmlResult };
}
