var MKT_V6_PIPELINE_STAGES=['OPPORTUNITY DETECTED','ELIGIBLE FOR CAMPAIGN','CAMPAIGN ACTIVE','RESPONDED','RFQ RECEIVED','QUOTED','LOAD / REACTIVATED','RETAINED / EXPANDED','COOLDOWN / NURTURE','CLOSED / SUPPRESSED'];
var MKT_V6_PIPELINE_RANK={'OPPORTUNITY DETECTED':1,'ELIGIBLE FOR CAMPAIGN':2,'CAMPAIGN ACTIVE':3,'RESPONDED':4,'RFQ RECEIVED':5,'QUOTED':6,'LOAD / REACTIVATED':7,'RETAINED / EXPANDED':8,'COOLDOWN / NURTURE':4,'CLOSED / SUPPRESSED':4};
function v6AccountPipeline_(){return {records:v6Rows_('MKT_ACCOUNT_PIPELINE')};}
function v6StageFromSignal_(p){if(p.dnc||p.hardSuppression)return 'CLOSED / SUPPRESSED';if(p.retained||p.expanded||p.crossSellSuccess)return 'RETAINED / EXPANDED';if(p.loadId||p.loadAt)return 'LOAD / REACTIVATED';if(p.quoteId||p.quoteAt)return 'QUOTED';if(p.rfqId||p.rfqAt)return 'RFQ RECEIVED';if(p.response||p.responseAt)return 'RESPONDED';if(p.campaignCompleted&&!p.responseAt)return 'COOLDOWN / NURTURE';return String(p.currentStage||p.stage||'OPPORTUNITY DETECTED').toUpperCase();}
function v6UpsertPipelineStage_(payload){var p=payload||{},id=String(p.accountId||'').trim();if(!id)throw new Error('accountId REQUIRED');var old=v6Rows_('MKT_ACCOUNT_PIPELINE').filter(function(r){return String(r.accountId||'')===id;})[0]||{},stage=v6StageFromSignal_(p);if(MKT_V6_PIPELINE_STAGES.indexOf(stage)<0)throw new Error('INVALID PIPELINE STAGE');if(p.preventDowngrade!==false&&old.currentStage&&MKT_V6_PIPELINE_RANK[stage]<MKT_V6_PIPELINE_RANK[old.currentStage])stage=old.currentStage;var changed=stage!==old.currentStage,now=new Date().toISOString(),record={accountId:id,accountName:p.accountName||old.accountName||'',amOwner:p.amOwner||old.amOwner||'',currentStage:stage,opportunityType:p.opportunityType||old.opportunityType||'',service:p.service||old.service||'',campaignId:p.campaignId||old.campaignId||'',executionId:p.executionId||old.executionId||'',enteredStageAt:changed?now:(old.enteredStageAt||now),lastMarketingTouchAt:p.lastMarketingTouchAt||old.lastMarketingTouchAt||'',responseAt:p.responseAt||old.responseAt||'',rfqAt:p.rfqAt||old.rfqAt||'',quoteAt:p.quoteAt||old.quoteAt||'',loadAt:p.loadAt||old.loadAt||'',cooldownUntil:p.cooldownUntil||old.cooldownUntil||'',nextAction:p.nextAction||old.nextAction||'',handoffStatus:p.handoffStatus||old.handoffStatus||'',attributedRevenue:p.attributedRevenue!=null?p.attributedRevenue:(old.attributedRevenue||''),updatedAt:now};if(stage==='RESPONDED'){record.nextAction='STOP ACCOUNT AUTOMATION / V5.5 HANDOFF';record.handoffStatus=p.handoffStatus||'PENDING';}return v6UpsertByKey_('MKT_ACCOUNT_PIPELINE',['accountId'],record);}
function v6PipelineTransition_(payload){return v6UpsertPipelineStage_(payload);}
function v6PipelineAdvanced_(stage){return ['CAMPAIGN ACTIVE','RESPONDED','RFQ RECEIVED','QUOTED','LOAD / REACTIVATED','RETAINED / EXPANDED','COOLDOWN / NURTURE'].indexOf(String(stage||'').toUpperCase())>=0;}
function v6PipelineLatest_(a,b){if(!a)return b;if(!b)return a;var ar=MKT_V6_PIPELINE_RANK[String(a.currentStage||'').toUpperCase()]||0,br=MKT_V6_PIPELINE_RANK[String(b.currentStage||'').toUpperCase()]||0;if(ar!==br)return br>ar?b:a;return String(b.updatedAt||b.enteredStageAt||'')>String(a.updatedAt||a.enteredStageAt||'')?b:a;}
function v6PipelineWinner_(a,b){if(!a)return b;var ad=String(a.eligibilityStatus||'').toUpperCase()!=='SUPPRESSED',bd=String(b.eligibilityStatus||'').toUpperCase()!=='SUPPRESSED';if(ad!==bd)return bd?b:a;var ap=Number(a.priorityRank||99),bp=Number(b.priorityRank||99);return bp<ap?b:a;}
function v6PipelineSyncSignals_(payload){var started=new Date().getTime(),opportunities=(payload||{}).opportunities;if(!Array.isArray(opportunities))opportunities=v6Rows_('MKT_OPPORTUNITIES');var table=v6Sheet_('MKT_ACCOUNT_PIPELINE');if(!table)throw new Error('MKT_ACCOUNT_PIPELINE NOT FOUND');var values=table.getDataRange().getValues(),headers=values.length?values.shift():[],existingByAccount={},winnerByAccount={};
  values.forEach(function(row){var record={};headers.forEach(function(h,i){record[h]=row[i];});var id=String(record.accountId||'').trim();if(id)existingByAccount[id]=v6PipelineLatest_(existingByAccount[id],record);});
  opportunities.forEach(function(o){var id=String(o.accountId||'').trim();if(id)winnerByAccount[id]=v6PipelineWinner_(winnerByAccount[id],o);});
  var now=new Date().toISOString(),created=0,updated=0,preserved=0,suppressed=0;Object.keys(winnerByAccount).forEach(function(id){var o=winnerByAccount[id],old=existingByAccount[id]||{},isSuppressed=String(o.eligibilityStatus||'').toUpperCase()==='SUPPRESSED',advanced=v6PipelineAdvanced_(old.currentStage),stage=advanced?old.currentStage:(isSuppressed?'CLOSED / SUPPRESSED':'OPPORTUNITY DETECTED'),changed=stage!==old.currentStage;if(isSuppressed)suppressed++;if(advanced)preserved++;if(old.accountId)updated++;else created++;existingByAccount[id]={accountId:id,accountName:o.accountName||old.accountName||'',amOwner:o.amOwner||old.amOwner||'',currentStage:stage,opportunityType:o.opportunityType||old.opportunityType||'',service:o.service||old.service||'',campaignId:old.campaignId||'',executionId:old.executionId||'',enteredStageAt:changed?now:(old.enteredStageAt||now),lastMarketingTouchAt:old.lastMarketingTouchAt||'',responseAt:old.responseAt||'',rfqAt:old.rfqAt||'',quoteAt:old.quoteAt||'',loadAt:old.loadAt||'',cooldownUntil:old.cooldownUntil||'',nextAction:advanced?(old.nextAction||''):(isSuppressed?'SUPPRESSED: '+String(o.suppressionReason||'UNSPECIFIED'):'EVALUATE CAMPAIGN ELIGIBILITY'),handoffStatus:old.handoffStatus||'',attributedRevenue:old.attributedRevenue||'',updatedAt:now};});
  var records=Object.keys(existingByAccount).sort().map(function(id){return existingByAccount[id];}),output=records.map(function(record){return headers.map(function(h){return record[h]==null?'':record[h];});});if(table.getLastRow()>1)table.getRange(2,1,table.getLastRow()-1,headers.length).clearContent();if(output.length)table.getRange(2,1,output.length,headers.length).setValues(output);return {status:'PIPELINE SYNCED',opportunityRows:opportunities.length,uniqueAccounts:Object.keys(winnerByAccount).length,created:created,updated:updated,preservedAdvancedStage:preserved,suppressed:suppressed,durationMs:new Date().getTime()-started};}
function v6PipelineSummary_(){var rows=v6Rows_('MKT_ACCOUNT_PIPELINE'),g={currentStage:{},opportunityType:{},service:{},amOwner:{}};rows.forEach(function(r){Object.keys(g).forEach(function(f){var k=String(r[f]||'UNSPECIFIED');g[f][k]=(g[f][k]||0)+1;});});return {total:rows.length,byCurrentStage:g.currentStage,byOpportunityType:g.opportunityType,byService:g.service,byAmOwner:g.amOwner};}
